/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.sql.*;
import java.util.regex.Pattern;

/**
 *
 * @author ashok
 */
public class CreateLedger extends javax.swing.JFrame {

    /**
     * Creates new form CreateLedger
     */
    public CreateLedger() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245,245,245));
        setTitle("Create Ledger");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mCreateLedgerTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mCreateLedgerTextFieldContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mCreateLedgerTextFieldEmail = new javax.swing.JTextField();
        mCreateLedgerComboBoxUnder = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mCreateLedgerTextFieldOpeningBalance = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        mCreateLedgerTextFieldAddress2 = new javax.swing.JTextField();
        mCreateLedgerTextFieldTown = new javax.swing.JTextField();
        mCreateLedgerTextFieldAddress1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mCreateLedgerTextFieldState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mCreateLedgerTextFieldCountry = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mCreateLedgerTextFieldZipCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mCreateLedgerTextFieldACno = new javax.swing.JTextField();
        mCreateLedgerButtonCancel = new javax.swing.JButton();
        mCreateLedgerButtonSubmit = new javax.swing.JButton();
        mCreateLedgerComboBoxUnit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ledger Creation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel1.setText("Name");

        mCreateLedgerTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldNameActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldNameKeyTyped(evt);
            }
        });

        jLabel2.setText("Contact No");

        mCreateLedgerTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldContactActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldContactKeyTyped(evt);
            }
        });

        jLabel3.setText("Email");

        mCreateLedgerTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mCreateLedgerTextFieldEmailFocusLost(evt);
            }
        });
        mCreateLedgerTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldEmailActionPerformed(evt);
            }
        });

        mCreateLedgerComboBoxUnder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Bank A/c", "Capital A/c", "Cash in Hand", "Current Asset", "Current Liability", "Direct Expenses", "Direct Income", "Fixed Asset", "Income Indirect", "Indirect Expense", "Investment", "Loans and Advances", "Loans Liability", "Purchase A/c", "Provision", "Reserves And Surplus", "Sales A/c", "Secured Loans", "Sundry Creditors", "Sundry Debtors", "Unsecured Loans ", "Suspense",}));
        mCreateLedgerComboBoxUnder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerComboBoxUnderActionPerformed(evt);
            }
        });

        jLabel4.setText("Under");

        jLabel5.setText("Opening Balance");

        mCreateLedgerTextFieldOpeningBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldOpeningBalanceActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldOpeningBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldOpeningBalanceKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Related Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel2.setFocusable(false);

        mCreateLedgerTextFieldAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldAddress2ActionPerformed(evt);
            }
        });

        mCreateLedgerTextFieldTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldTownActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldTown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldTownKeyTyped(evt);
            }
        });

        mCreateLedgerTextFieldAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldAddress1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Address Line 1");

        jLabel8.setText("Town/City");

        jLabel6.setText("Address Line 2");

        jLabel9.setText("State");

        mCreateLedgerTextFieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldStateActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldStateKeyTyped(evt);
            }
        });

        jLabel10.setText("Country");

        mCreateLedgerTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldCountryActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldCountryKeyTyped(evt);
            }
        });

        jLabel11.setText("Zip Code");

        mCreateLedgerTextFieldZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldZipCodeActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldZipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldZipCodeKeyTyped(evt);
            }
        });

        jLabel12.setText("A/c No (if Under As Bank A/c)");

        mCreateLedgerTextFieldACno.setEditable(false);
        mCreateLedgerTextFieldACno.setBackground(new java.awt.Color(245, 245, 245));
        mCreateLedgerTextFieldACno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerTextFieldACnoActionPerformed(evt);
            }
        });
        mCreateLedgerTextFieldACno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mCreateLedgerTextFieldACnoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(mCreateLedgerTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(mCreateLedgerTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCreateLedgerTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(mCreateLedgerTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(mCreateLedgerTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mCreateLedgerTextFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(mCreateLedgerTextFieldACno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCreateLedgerTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCreateLedgerTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mCreateLedgerTextFieldACno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mCreateLedgerButtonCancel.setText("Cancel");
        mCreateLedgerButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerButtonCancelActionPerformed(evt);
            }
        });

        mCreateLedgerButtonSubmit.setText("Submit");
        mCreateLedgerButtonSubmit.setToolTipText("submit");
        mCreateLedgerButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCreateLedgerButtonSubmitActionPerformed(evt);
            }
        });

        mCreateLedgerComboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cr", "Dr" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mCreateLedgerComboBoxUnder, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mCreateLedgerTextFieldName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(mCreateLedgerTextFieldOpeningBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mCreateLedgerComboBoxUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mCreateLedgerTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mCreateLedgerTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(32, 32, 32))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mCreateLedgerButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mCreateLedgerButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCreateLedgerTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCreateLedgerComboBoxUnder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerTextFieldOpeningBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCreateLedgerComboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCreateLedgerButtonCancel)
                    .addComponent(mCreateLedgerButtonSubmit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void mCreateLedgerTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void mCreateLedgerTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mCreateLedgerTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

    private void mCreateLedgerTextFieldOpeningBalanceActionPerformed(java.awt.event.ActionEvent evt) {                                                                     
        // TODO add your handling code here:
    }                                                                    

    private void mCreateLedgerTextFieldTownActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void mCreateLedgerTextFieldAddress2ActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mCreateLedgerTextFieldAddress1ActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mCreateLedgerTextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

    private void mCreateLedgerTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mCreateLedgerTextFieldZipCodeActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mCreateLedgerButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        
        if((mCreateLedgerTextFieldName.getText().trim().equals(""))) 
        {
            JOptionPane.showMessageDialog(new JFrame(),"Name can't be empty");
        }
  
//       else if((mCreateLedgerTextFieldOpeningBalance.getText().trim().equals(""))) 
//        {
//            JOptionPane.showMessageDialog(new JFrame(),"Opening Balance can't be empty");
//        }
        else if(mCreateLedgerComboBoxUnder.getSelectedItem().toString().equals("Select"))
        {
              JOptionPane.showMessageDialog(new JFrame(),"Select Under");
        }
        else if((mCreateLedgerTextFieldACno.getText().length()>0)&&(mCreateLedgerTextFieldACno.getText().length()<14))
        {
              JOptionPane.showMessageDialog(new JFrame(),"A/C must be of 14 digits");
        }
        else if((mCreateLedgerTextFieldContact.getText().length()>0)&&(mCreateLedgerTextFieldContact.getText().length()<10))
        {
              JOptionPane.showMessageDialog(new JFrame(),"Contact must be of 10 digits");
        }
        else if((mCreateLedgerTextFieldZipCode.getText().length()>0)&&(mCreateLedgerTextFieldZipCode.getText().length()<6))
        {
              JOptionPane.showMessageDialog(new JFrame(),"ZIP code must be of 6 digits");
        }
        else
        {
        
            try
		{
              	Connection con = dao.createconnection();
                String sql="insert into  Ledger_Create values(?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement st = con.prepareStatement(sql);
                st.setString(1,mCreateLedgerTextFieldName.getText() );
		st.setString(2,mCreateLedgerTextFieldContact.getText() );
		st.setString(3,mCreateLedgerTextFieldEmail.getText());
                st.setString(4,(String)mCreateLedgerComboBoxUnder.getSelectedItem());
                st.setString(5,mCreateLedgerTextFieldOpeningBalance.getText());
                st.setString(6,mCreateLedgerTextFieldAddress1.getText() );
                st.setString(7,mCreateLedgerTextFieldAddress2.getText() );
                st.setString(8,mCreateLedgerTextFieldTown.getText() );
                st.setString(9,mCreateLedgerTextFieldState.getText() );
                st.setString(10,mCreateLedgerTextFieldCountry.getText());
                st.setString(11,mCreateLedgerTextFieldZipCode.getText());
                st.setString(12,mCreateLedgerTextFieldACno.getText());
                 int flag=st.executeUpdate();
                 if(flag>0)
		{
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Record Inserted Successfully");
		mCreateLedgerTextFieldName.setText("");
                mCreateLedgerTextFieldContact.setText("");
                mCreateLedgerTextFieldEmail.setText("");
                mCreateLedgerComboBoxUnder.setSelectedIndex(0);
                mCreateLedgerTextFieldOpeningBalance.setText("");
                mCreateLedgerTextFieldAddress1.setText("");
                mCreateLedgerTextFieldAddress2.setText("");
                mCreateLedgerTextFieldTown.setText("");
                mCreateLedgerTextFieldState.setText("");
                mCreateLedgerTextFieldCountry.setText("");
                mCreateLedgerTextFieldZipCode.setText("");
                mCreateLedgerTextFieldACno.setText("");	    
                }}catch(Exception e)
                {
                    JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Ledger Already Exists");
                e.printStackTrace();
                }

            
            
        
        }
        
        
    }                                                         

    private void mCreateLedgerTextFieldACnoActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void mCreateLedgerTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void mCreateLedgerTextFieldContactKeyTyped(java.awt.event.KeyEvent evt) {                                                       
        // TODO add your handling code here:
       char c=evt.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    evt.consume();//ignore event
                }
                else if(mCreateLedgerTextFieldContact.getText().length()>9)
                {
                   evt.consume();
                }
    }                                                      

    private void mCreateLedgerTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {                                                    
        // TODO add your handling code here:
       
    }                                                   

    private void mCreateLedgerTextFieldTownKeyTyped(java.awt.event.KeyEvent evt) {                                                    
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    evt.consume();//ignore event
                }
    }                                                   

    private void mCreateLedgerTextFieldStateKeyTyped(java.awt.event.KeyEvent evt) {                                                     
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    evt.consume();//ignore event
                }
    }                                                    

    private void mCreateLedgerTextFieldCountryKeyTyped(java.awt.event.KeyEvent evt) {                                                       
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    evt.consume();//ignore event
               }
    }                                                      

    private void mCreateLedgerTextFieldZipCodeKeyTyped(java.awt.event.KeyEvent evt) {                                                       
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    evt.consume();//ignore event
                }
                else if(mCreateLedgerTextFieldZipCode.getText().length()>5)
                {
                   evt.consume();
                }
    }                                                      

    private void mCreateLedgerTextFieldACnoKeyTyped(java.awt.event.KeyEvent evt) {                                                    
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    evt.consume();//ignore event
                }
                else if(mCreateLedgerTextFieldACno.getText().length()>13)
                {
                   evt.consume();
                }
    }                                                   

    private void mCreateLedgerTextFieldOpeningBalanceKeyTyped(java.awt.event.KeyEvent evt) {                                                              
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    evt.consume();//ignore event
                }
                else if(mCreateLedgerTextFieldOpeningBalance.getText().length()>8)
                {
                   evt.consume();
                }
    }                                                             

    private void mCreateLedgerTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {                                                      
        // TODO add your handling code here:
        if(mCreateLedgerTextFieldEmail.getText().trim().length()>0)
        				{
        			        Pattern pattern3 = Pattern.compile("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$", Pattern.CASE_INSENSITIVE);
           				Matcher m3=pattern3.matcher(mCreateLedgerTextFieldEmail.getText());
           				Boolean b3=m3.matches();
           				if(b3!=true)
           				{
           				    JOptionPane.showMessageDialog(new JFrame(),"Invalid Email Address");
           				}
                                        }
    }                                                     

    private void mCreateLedgerComboBoxUnderActionPerformed(java.awt.event.ActionEvent evt) {                                                           
    
        mCreateLedgerComboBoxUnder=(JComboBox)evt.getSource();
        
        if(mCreateLedgerComboBoxUnder.getSelectedItem().toString().equals("Bank A/c"))
        { 
         mCreateLedgerTextFieldACno.setEditable(true);
        mCreateLedgerTextFieldACno.setBackground(new java.awt.Color(255,255,255));
        }
       
        else
       {
         mCreateLedgerTextFieldACno.setText("");   
         mCreateLedgerTextFieldACno.setEditable(false);
         mCreateLedgerTextFieldACno.setBackground(new java.awt.Color(245,245,245));

       }
    }                                                          

    private void mCreateLedgerButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {                                                          
new Ledger().setVisible(true);
        // TODO add your handling code here:
        // TODO add your handling code here:
        dispose();
    }                                                         

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
new Ledger().setVisible(true); 
      dispose();// TODO add your handling code here:
              // TODO add your handling code here:
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLedger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLedger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLedger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLedger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLedger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mCreateLedgerButtonCancel;
    private javax.swing.JButton mCreateLedgerButtonSubmit;
    private javax.swing.JComboBox<String> mCreateLedgerComboBoxUnder;
    private javax.swing.JComboBox<String> mCreateLedgerComboBoxUnit;
    private javax.swing.JTextField mCreateLedgerTextFieldACno;
    private javax.swing.JTextField mCreateLedgerTextFieldAddress1;
    private javax.swing.JTextField mCreateLedgerTextFieldAddress2;
    private javax.swing.JTextField mCreateLedgerTextFieldContact;
    private javax.swing.JTextField mCreateLedgerTextFieldCountry;
    private javax.swing.JTextField mCreateLedgerTextFieldEmail;
    private javax.swing.JTextField mCreateLedgerTextFieldName;
    private javax.swing.JTextField mCreateLedgerTextFieldOpeningBalance;
    private javax.swing.JTextField mCreateLedgerTextFieldState;
    private javax.swing.JTextField mCreateLedgerTextFieldTown;
    private javax.swing.JTextField mCreateLedgerTextFieldZipCode;
    // End of variables declaration                   
}
