/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

import javax.swing.table.TableCellRenderer;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.AbstractTableModel;
import java.awt.event.*;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.table.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class DayBook extends javax.swing.JFrame {

    /**
     * Creates new form DayBook
     */
    public DayBook() {
        initComponents();
        setTitle("Day Book");
       getContentPane().setBackground(new java.awt.Color(245,245,245));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Account Section");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Day Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jTable1.setRowSelectionAllowed(true);
        //jTable1.setEnabled(false);
        jTable1.setRowHeight(25);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Particulars", "Vch Type", "Vch No.", "Debit Amount", "Credit Amount"
            }
        ));
        try{
            DefaultTableModel model1=(DefaultTableModel)jTable1.getModel();

            Connection con=dao.createconnection();
            String sq="select * from vouchers";
            PreparedStatement st = con.prepareStatement(sq);
            ResultSet r=st.executeQuery();
            r.last();
            model1.addRow(new Object[]{r.getString(2),r.getString(4),r.getString(7),r.getInt(1),r.getInt(5),r.getInt(6)});
            while(r.previous())
            {
                model1.addRow(new Object[]{r.getString(2),r.getString(4),r.getString(7),r.getInt(1),r.getInt(5),r.getInt(6)});
            }
        }
        catch(Exception e1)
        {
        }

        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        javax.swing.JTextField textBox3=new JTextField();      //shweta
        TableColumn soprtColumn3=jTable1.getColumnModel().getColumn(2);
        soprtColumn3.setCellEditor(new DefaultCellEditor (textBox3));
        //jTable1.setCellSelectionEnabled(true);

        textBox3.addKeyListener(new KeyAdapter()
            {
                public void keyPressed(KeyEvent evt)
                {
                    if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                    {
                        evt.consume();//ignore event
                    }

                }
                public void keyTyped(KeyEvent evt)
                {
                    char c=evt.getKeyChar();
                    if(c>=0 && c<=127)
                    {
                        evt.consume();//ignore event
                    }
                }

            });
            javax.swing.JTextField textBox4=new JTextField();      //shweta
            TableColumn soprtColumn4=jTable1.getColumnModel().getColumn(0);
            soprtColumn4.setCellEditor(new DefaultCellEditor (textBox4));
            //jTable1.setCellSelectionEnabled(true);

            textBox4.addKeyListener(new KeyAdapter()
                {
                    public void keyPressed(KeyEvent evt)
                    {
                        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                        {
                            evt.consume();//ignore event
                        }

                    }
                    public void keyTyped(KeyEvent evt)
                    {
                        char c=evt.getKeyChar();
                        if(c>=0 && c<=127)
                        {
                            evt.consume();//ignore event
                        }
                    }

                });

                javax.swing.JTextField textBox5=new JTextField();      //shweta
                TableColumn soprtColumn5=jTable1.getColumnModel().getColumn(1);
                soprtColumn5.setCellEditor(new DefaultCellEditor (textBox5));
                //jTable1.setCellSelectionEnabled(true);

                textBox5.addKeyListener(new KeyAdapter()
                    {
                        public void keyPressed(KeyEvent evt)
                        {
                            if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                            {
                                evt.consume();//ignore event
                            }

                        }
                        public void keyTyped(KeyEvent evt)
                        {
                            char c=evt.getKeyChar();
                            if(c>=0 && c<=127)
                            {
                                evt.consume();//ignore event
                            }
                        }

                    });
                    javax.swing.JTextField textBox6=new JTextField();      //shweta
                    TableColumn soprtColumn6=jTable1.getColumnModel().getColumn(3);
                    soprtColumn6.setCellEditor(new DefaultCellEditor (textBox6));
                    //jTable1.setCellSelectionEnabled(true);

                    textBox6.addKeyListener(new KeyAdapter()
                        {
                            public void keyPressed(KeyEvent evt)
                            {
                                if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                                {
                                    evt.consume();//ignore event
                                }

                            }
                            public void keyTyped(KeyEvent evt)
                            {
                                char c=evt.getKeyChar();
                                if(c>=0 && c<=127)
                                {
                                    evt.consume();//ignore event
                                }
                            }

                        });
                        javax.swing.JTextField textBox7=new JTextField();      //shweta
                        TableColumn soprtColumn7=jTable1.getColumnModel().getColumn(4);
                        soprtColumn7.setCellEditor(new DefaultCellEditor (textBox7));
                        //jTable1.setCellSelectionEnabled(true);

                        textBox7.addKeyListener(new KeyAdapter()
                            {
                                public void keyPressed(KeyEvent evt)
                                {
                                    if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                                    {
                                        evt.consume();//ignore event
                                    }

                                }
                                public void keyTyped(KeyEvent evt)
                                {
                                    char c=evt.getKeyChar();
                                    if(c>=0 && c<=127)
                                    {
                                        evt.consume();//ignore event
                                    }
                                }

                            });
                            javax.swing.JTextField textBox8=new JTextField();      //shweta
                            TableColumn soprtColumn8=jTable1.getColumnModel().getColumn(5);
                            soprtColumn8.setCellEditor(new DefaultCellEditor (textBox8));
                            //jTable1.setCellSelectionEnabled(true);

                            textBox8.addKeyListener(new KeyAdapter()
                                {
                                    public void keyPressed(KeyEvent evt)
                                    {
                                        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                                        {
                                            evt.consume();//ignore event
                                        }

                                    }
                                    public void keyTyped(KeyEvent evt)
                                    {
                                        char c=evt.getKeyChar();
                                        if(c>=0 && c<=127)
                                        {
                                            evt.consume();//ignore event
                                        }
                                    }

                                });
                                jScrollPane1.setViewportView(jTable1);

                                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                                jPanel1.setLayout(jPanel1Layout);
                                jPanel1Layout.setHorizontalGroup(
                                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                                        .addContainerGap())
                                );
                                jPanel1Layout.setVerticalGroup(
                                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                        .addContainerGap())
                                );

                                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                getContentPane().setLayout(layout);
                                layout.setHorizontalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                );
                                layout.setVerticalGroup(
                                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                );

                                pack();
                                setLocationRelativeTo(null);
                            }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       int row=jTable1.getSelectedRow();
       String vou=model.getValueAt(row,2).toString();
       int vono=Integer.parseInt(model.getValueAt(row,3).toString());
       if(vou.equals("Receipt"))
       {
          new Receipt(vono).setVisible(true);
          dispose();
       }
       else if(vou.equals("Payment"))
       {
        new Payment(vono).setVisible(true);       
       dispose();
       }
       else if(vou.equals("Sales"))
       {
        new Sales(vono).setVisible(true);       
       dispose();
       }
       else if(vou.equals("Purchase"))
       {
        new Purchase(vono).setVisible(true);       
       dispose();
       }
       else if(vou.equals("Journal"))
       {
        new Journel(vono).setVisible(true);       
       dispose();
       }


    }                                    

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
 new Dashboard().setVisible(true); 
      dispose();        // TODO add your handling code here:
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DayBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DayBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DayBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DayBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DayBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}

