/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

import java.io.*;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.awt.FileDialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class EmployeeModify extends javax.swing.JFrame {
 int m=0;
 JFrame fr;
String path;
Image oimg,simg;
String val;
String access="";
int p;
    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeModify(String value1,int t,JFrame ft) {
      p=t;
      fr=ft;
 val=value1; 
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/modify.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldAddessLine1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldAddessLine2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldTown = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldState = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldCountry = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldZIPCode = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldAlternateContactNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldContactNo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mAddVendorTextFieldFirstName1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldSalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldEmployeeID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        mEmployeeModifyComboBoxDepartment = new javax.swing.JComboBox<>();
        mEmployeeModifyComboBoxWorkLocation = new javax.swing.JComboBox<>();
        mEmployeeModifyComboBoxSalary = new javax.swing.JComboBox<>();
        mEmployeeModifyComboBoxSupervisor = new javax.swing.JComboBox<>();
        mEmployeeModifyTextFieldDesignation = new javax.swing.JTextField();
        mModifyEmployeeComboBoxDate1 = new javax.swing.JComboBox<>();
        mModifyEmployeeComboBoxMonth1 = new javax.swing.JComboBox<>();
        mModifyEmployeeComboBoxYear1 = new javax.swing.JComboBox<>();
        mEmployeeModifyCheckBoxInvoice = new javax.swing.JCheckBox();
        mEmployeeModifyCheckBoxInventory = new javax.swing.JCheckBox();
        mEmployeeModifyCheckBoxAccount = new javax.swing.JCheckBox();
        mEmployeeModifyCheckBoxEmployee = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldContactNo1 = new javax.swing.JTextField();
        mEmployeeModifyTextFieldEmail1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldRelationship = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mEmployelabelPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mEmployeeModifyTextFieldLastName = new javax.swing.JTextField();
        mEmployeeModifyRadioButtonFemale = new javax.swing.JRadioButton();
        mEmployeeModifyRadioButtonMale = new javax.swing.JRadioButton();
        mEmployeeModifyTextFieldNationality = new javax.swing.JTextField();
        mEmployeModifyTextFieldAadharNumber = new javax.swing.JTextField();
        mEmployeeModifyComboBoxDate = new javax.swing.JComboBox<>();
        mEmployeeModifyComboBoxMonth = new javax.swing.JComboBox<>();
        mModifyEmployeeComboBoxYear = new javax.swing.JComboBox<>();
        mEmployelabelReset = new javax.swing.JLabel();
        mEmployelabelBrowse = new javax.swing.JLabel();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent){
              if(p==0)
              {
                  dispose();
                  new EmployeeDashboard(fr).setVisible(true);
              }
              else
              {
                  dispose();
                  fr.setEnabled(true);
              }
                
         }        
      });
setTitle("Modify Employee Details");
        setBounds(new java.awt.Rectangle(277, 70, 812, 582));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(792, 754));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(760, 730));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel7.setText("Address Line 1");
mEmployeeModifyComboBoxSupervisor.addItem("Select");
		  try
				{
					Connection con = dao.createconnection();
					PreparedStatement ps0 = con.prepareStatement("select * from employee1");
					ResultSet rs0 = ps0.executeQuery();
					while(rs0.next())
					{
					String id=rs0.getString(16);
					mEmployeeModifyComboBoxSupervisor.addItem(""+id);
					}
				
					
				}
				catch(Exception ee)
				{
				}





        mEmployeeModifyTextFieldAddessLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldAddessLine1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Address Line 2");

        mEmployeeModifyTextFieldAddessLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldAddessLine2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Town/City");

        mEmployeeModifyTextFieldTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldTownActionPerformed(evt);
            }
        });
        mEmployeeModifyTextFieldTown.addKeyListener(new KeyAdapter()       // validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });

        jLabel12.setText("State");

        mEmployeeModifyTextFieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldStateActionPerformed(evt);
            }
        });

        mEmployeeModifyTextFieldState.addKeyListener(new KeyAdapter()             //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });
        

        mEmployeeModifyTextFieldCountry.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });
        

        
        mEmployeeModifyTextFieldZIPCode.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeeModifyTextFieldZIPCode.getText().length()>5)
                {
                   e.consume();
                }
               
            }
        });
        
        
        mEmployeeModifyTextFieldAlternateContactNo.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeeModifyTextFieldAlternateContactNo.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });
        
        mEmployeeModifyTextFieldContactNo.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeeModifyTextFieldContactNo.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });

        mEmployeeModifyTextFieldEmail.addFocusListener(new FocusAdapter()      //validation
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{
				if(mEmployeeModifyTextFieldEmail.getText().trim().length()>0)
        				{
        			        Pattern pattern3 = Pattern.compile("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$", Pattern.CASE_INSENSITIVE);
           				Matcher m3=pattern3.matcher(mEmployeeModifyTextFieldEmail.getText());
           				Boolean b3=m3.matches();
           				if(b3!=true)
           				{
           				    JOptionPane.showMessageDialog(new JFrame(),"Invalid Email Address");
           				}
      			}
		}	
		});




        jLabel13.setText("Country");

        mEmployeeModifyTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldCountryActionPerformed(evt);
            }
        });

        jLabel14.setText("ZIP Code");

        mEmployeeModifyTextFieldZIPCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldZIPCodeActionPerformed(evt);
            }
        });

        jLabel25.setText("Email");

        mEmployeeModifyTextFieldAlternateContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldAlternateContactNoActionPerformed(evt);
            }
        });

        jLabel19.setText("Contact No");

        mEmployeeModifyTextFieldContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldContactNoActionPerformed(evt);
            }
        });

        jLabel35.setText("Alternate Contact No");

        mEmployeeModifyTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mEmployeeModifyTextFieldState, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(mEmployeeModifyTextFieldAddessLine1))
                            .addComponent(mEmployeeModifyTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(mEmployeeModifyTextFieldAlternateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mEmployeeModifyTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(mEmployeeModifyTextFieldAddessLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mEmployeeModifyTextFieldZIPCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mEmployeeModifyTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mEmployeeModifyTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeeModifyTextFieldAddessLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldAddessLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mEmployeeModifyTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mEmployeeModifyTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mEmployeeModifyTextFieldZIPCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel35)
                    .addComponent(jLabel25))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeeModifyTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldAlternateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(245, 245, 245));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Reset");
jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
jButton1.setToolTipText("Reset");
	jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));


        jButton2.setBackground(new java.awt.Color(245, 245, 245));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
jButton2.setToolTipText("Delete");
	jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        jButton3.setBackground(new java.awt.Color(245, 245, 245));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
jButton3.setToolTipText("Cancel");
	jButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        mAddVendorTextFieldFirstName1.setBackground(new java.awt.Color(245, 245, 245));
        mAddVendorTextFieldFirstName1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Job Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel15.setText("Designation");

        mEmployeeModifyTextFieldSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldSalaryActionPerformed(evt);
            }
        });
mEmployeeModifyTextFieldDesignation.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)))
               {
                    e.consume();//ignore event
                }
                
            }
        });

        mEmployeeModifyTextFieldSalary.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeeModifyTextFieldSalary.getText().length()>7)
                {
                   e.consume();
                }
               
            }
        });
        
        jLabel16.setText("Work Location");

        jLabel20.setText("Supervisor");

        jLabel22.setText("Salary");

        jLabel23.setText("Employee ID");

        mEmployeeModifyTextFieldEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldEmployeeIDActionPerformed(evt);
            }
        });

        jLabel24.setText("Department");

        jLabel29.setText("Date of Joining");

        jLabel31.setText("Acess Rights");

        mEmployeeModifyComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "Select", "Production", "Quality", "Sales and Purchasing","IT","Health and Safety","Technical Planning","Corporate Support","Accounting" }));

        mEmployeeModifyComboBoxWorkLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Godown", "House", "Factory" }));
        mEmployeeModifyComboBoxWorkLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyComboBoxWorkLocationActionPerformed(evt);
            }
        });

        mEmployeeModifyComboBoxSalary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "per day", "per month" }));

     //   mEmployeeModifyComboBoxSupervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05", "06", "07", "08", "09", "100" }));

        mEmployeeModifyTextFieldDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldDesignationActionPerformed(evt);
            }
        });

        mModifyEmployeeComboBoxDate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mModifyEmployeeComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        mModifyEmployeeComboBoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        mEmployeeModifyCheckBoxInvoice.setText("Invoicing");
        mEmployeeModifyCheckBoxInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyCheckBoxInvoiceActionPerformed(evt);
            }
        });

        mEmployeeModifyCheckBoxInventory.setText("Inventory");
        mEmployeeModifyCheckBoxInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyCheckBoxInventoryActionPerformed(evt);
            }
        });

        mEmployeeModifyCheckBoxAccount.setText("Accounts");
        mEmployeeModifyCheckBoxAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyCheckBoxAccountActionPerformed(evt);
            }
        });

        mEmployeeModifyCheckBoxEmployee.setText("Employees");
        mEmployeeModifyCheckBoxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyCheckBoxEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mAddVendorTextFieldFirstName1Layout = new javax.swing.GroupLayout(mAddVendorTextFieldFirstName1);
        mAddVendorTextFieldFirstName1.setLayout(mAddVendorTextFieldFirstName1Layout);
        mAddVendorTextFieldFirstName1Layout.setHorizontalGroup(
            mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel16)
                                .addComponent(mEmployeeModifyTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel15)
                                .addComponent(mEmployeeModifyTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mEmployeeModifyComboBoxWorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mModifyEmployeeComboBoxDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mModifyEmployeeComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mModifyEmployeeComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)))
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mEmployeeModifyCheckBoxInvoice)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mEmployeeModifyCheckBoxInventory))
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mEmployeeModifyTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(mEmployeeModifyComboBoxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel31))
                            .addGap(20, 20, 20)))
                    .addComponent(jLabel29))
                .addGap(25, 25, 25)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20)
                            .addComponent(mEmployeeModifyComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mEmployeeModifyComboBoxSupervisor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                .addComponent(mEmployeeModifyCheckBoxAccount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mEmployeeModifyCheckBoxEmployee)))
                        .addGap(30, 30, 30))))
        );
        mAddVendorTextFieldFirstName1Layout.setVerticalGroup(
            mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeeModifyComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeeModifyComboBoxWorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyComboBoxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyComboBoxSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mModifyEmployeeComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mModifyEmployeeComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mModifyEmployeeComboBoxDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyCheckBoxInvoice)
                    .addComponent(mEmployeeModifyCheckBoxInventory)
                    .addComponent(mEmployeeModifyCheckBoxAccount)
                    .addComponent(mEmployeeModifyCheckBoxEmployee))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Emergency Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel30.setText("Name");

        mEmployeeModifyTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldNameActionPerformed(evt);
            }
        });

        mEmployeeModifyTextFieldName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });



        mEmployeeModifyTextFieldContactNo1.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeeModifyTextFieldContactNo1.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });
        

        mEmployeeModifyTextFieldEmail1.addFocusListener(new FocusAdapter()
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{
				if(mEmployeeModifyTextFieldEmail1.getText().trim().length()>0)
        				{
        			                   Pattern pattern3 = Pattern.compile("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$", Pattern.CASE_INSENSITIVE);
           				Matcher m3=pattern3.matcher(mEmployeeModifyTextFieldEmail1.getText());
           				Boolean b3=m3.matches();
           				if(b3!=true)
           				{
           				    JOptionPane.showMessageDialog(new JFrame(),"Invalid Email Address");
           				}
      			}
		}	
		});

        
        
        mEmployeeModifyTextFieldRelationship.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)))
               {
                    e.consume();//ignore event
                }
                
            }
        });



        jLabel32.setText("Contact No");

        jLabel33.setText("Email");

        mEmployeeModifyTextFieldContactNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldContactNo1ActionPerformed(evt);
            }
        });

        mEmployeeModifyTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldEmail1ActionPerformed(evt);
            }
        });

        jLabel34.setText("Relationship");

        mEmployeeModifyTextFieldRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyTextFieldRelationshipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployeeModifyTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployeeModifyTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(mEmployeeModifyTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(mEmployeeModifyTextFieldRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeeModifyTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeeModifyTextFieldRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(245, 245, 245));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
	jButton4.setToolTipText("Save Changes");
	jButton4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        //mEmployelabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/new user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        mEmployeeModifyTextFieldFirstName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");



        mEmployeeModifyTextFieldLastName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });

        
        mEmployeeModifyTextFieldNationality.addKeyListener(new KeyAdapter() 
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });

        
        
        mEmployeModifyTextFieldAadharNumber.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeModifyTextFieldAadharNumber.getText().length()>11)
                {
                   e.consume();
                }
               
            }
        });
        

        mEmployelabelBrowse.setToolTipText("Browse Photo");
        mEmployelabelBrowse.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mEmployelabelReset.setToolTipText("Reset Photo");
        mEmployelabelReset.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        
      mEmployelabelBrowse.addMouseListener(new MouseAdapter()
	{    
         
		public void mouseClicked(MouseEvent me)
		{
			FileDialog fd = new FileDialog(new javax.swing.JFrame (),"Choose Photo",FileDialog.LOAD);
			fd.setVisible(true);
			path = fd.getDirectory()+fd.getFile();
			if(!path.equals("nullnull"))
			{
				oimg = Toolkit.getDefaultToolkit().getImage(path);	
				simg = oimg.getScaledInstance(100,100,Image.SCALE_DEFAULT);   
				ImageIcon icon = new ImageIcon(simg);
				mEmployelabelPhoto.setIcon(icon); 
				m=1;
			}
		}
	});	

 mEmployelabelReset.addMouseListener(new MouseAdapter()
	{   
	  
              
		public void mouseClicked(MouseEvent me)
		{
      			mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));
		}
	});

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Nationality");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Date of Birth");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Aadhar Number");

        mEmployeeModifyRadioButtonFemale.setText("Female");
        mEmployeeModifyRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeeModifyRadioButtonFemaleActionPerformed(evt);
            }
        });

        mEmployeeModifyRadioButtonMale.setText("Male");
      bg =new ButtonGroup();
        bg.add(mEmployeeModifyRadioButtonFemale);
        bg.add(mEmployeeModifyRadioButtonMale);

        mEmployeeModifyComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mEmployeeModifyComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        mModifyEmployeeComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        mEmployelabelReset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployelabelReset.setForeground(new java.awt.Color(0, 0, 255));
        mEmployelabelReset.setText("<html><u>Reset</u></html>");

        mEmployelabelBrowse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployelabelBrowse.setForeground(new java.awt.Color(0, 0, 255));
        mEmployelabelBrowse.setText("<html><u>Browse</u></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mEmployelabelBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mEmployelabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mEmployelabelPhoto))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(107, 107, 107))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(mEmployeeModifyTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mEmployeeModifyTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mEmployeeModifyRadioButtonMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mEmployeeModifyRadioButtonFemale))
                            .addComponent(jLabel3)
                            .addComponent(mEmployeeModifyTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mEmployeeModifyComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mEmployeeModifyComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mModifyEmployeeComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mEmployeModifyTextFieldAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mEmployeeModifyComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mModifyEmployeeComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mEmployeeModifyComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mEmployeeModifyTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mEmployeeModifyTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mEmployeeModifyRadioButtonMale)
                                    .addComponent(mEmployeeModifyTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mEmployeeModifyRadioButtonFemale)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEmployeModifyTextFieldAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(mEmployelabelPhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployelabelBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployelabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mAddVendorTextFieldFirstName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mAddVendorTextFieldFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

    mEmployeeModifyTextFieldEmployeeID.setEditable(false);
    mEmployeeModifyTextFieldFirstName.setEditable(false);
    mEmployeeModifyTextFieldLastName.setEditable(false);
 mEmployeModifyTextFieldAadharNumber.setEditable(false);
    mEmployeeModifyTextFieldNationality.setEditable(false);
   
		mEmployeeModifyComboBoxDate.setEnabled(false);
		mEmployeeModifyComboBoxMonth.setEnabled(false);
		mModifyEmployeeComboBoxYear.setEnabled(false);
		mModifyEmployeeComboBoxDate1.setEnabled(false);
		mModifyEmployeeComboBoxMonth1.setEnabled(false);
		mModifyEmployeeComboBoxYear1.setEnabled(false);
		mEmployeeModifyRadioButtonMale.setEnabled(false);
		mEmployeeModifyRadioButtonFemale.setEnabled(false);



try
				{
					Connection con1 = dao.createconnection();
					PreparedStatement ps = con1.prepareStatement("select * from employee1 where EmployeeId=?");
					ps.setString(1,val);
					ResultSet rs = ps.executeQuery();
					if(rs.next())
					{



                mEmployeeModifyTextFieldFirstName.setText(rs.getString(1));
                mEmployeeModifyTextFieldLastName.setText(rs.getString(2));
                	String dt[] = rs.getString(3).split("-");
	 mEmployeeModifyComboBoxDate.setSelectedItem(dt[0]);
	 mEmployeeModifyComboBoxMonth.setSelectedItem(dt[1]);
	  mModifyEmployeeComboBoxYear.setSelectedItem(dt[2]);
											
                   mEmployeeModifyTextFieldNationality.setText(rs.getString(4));
                   
	String gen = rs.getString(5);
			if(gen.equals("Male"))
					{
					mEmployeeModifyRadioButtonMale.getModel().setSelected(true);
					}
					else
					{
					mEmployeeModifyRadioButtonFemale.getModel().setSelected(true);
					}
						

                   mEmployeModifyTextFieldAadharNumber.setText(rs.getString(6));
                    mEmployeeModifyTextFieldAddessLine1.setText(rs.getString(7));
                    mEmployeeModifyTextFieldAddessLine2.setText(rs.getString(8));
                    mEmployeeModifyTextFieldTown.setText(rs.getString(9));
                    mEmployeeModifyTextFieldState.setText(rs.getString(10));
                    mEmployeeModifyTextFieldCountry.setText(rs.getString(11));
                    mEmployeeModifyTextFieldZIPCode.setText(rs.getString(12));
                    mEmployeeModifyTextFieldContactNo.setText(rs.getString(13));
                    mEmployeeModifyTextFieldAlternateContactNo.setText(rs.getString(14));
                   mEmployeeModifyTextFieldEmail.setText(rs.getString(15));
                    mEmployeeModifyTextFieldEmployeeID.setText(rs.getString(16));
                     mEmployeeModifyTextFieldDesignation.setText(rs.getString(17));

	 mEmployeeModifyComboBoxDepartment.setSelectedItem(rs.getString(18));
	 mEmployeeModifyComboBoxSupervisor.setSelectedItem(rs.getString(21));
						       
mEmployeeModifyComboBoxWorkLocation.setSelectedItem(rs.getString(19));

                
String dt1[] = rs.getString(20).split(" ");
mEmployeeModifyTextFieldSalary.setText(dt1[0]);
mEmployeeModifyComboBoxSalary.setSelectedItem(dt1[1]+" "+dt1[2]);

                 String dt2[]=rs.getString(22).split("-");
	mModifyEmployeeComboBoxDate1.setSelectedItem(dt2[0]);
	 mModifyEmployeeComboBoxMonth1.setSelectedItem(dt2[1]);
	 mModifyEmployeeComboBoxYear1.setSelectedItem(dt2[2]);

	 String st[]=rs.getString(23).split(" ");
	for(int m=0;m<st.length;m++)
	{
		if(st[m].equals("Invoice"))
		{
			mEmployeeModifyCheckBoxInvoice.setSelected(true);
		}
		if(st[m].equals("Inventory"))
		{
			mEmployeeModifyCheckBoxInventory.setSelected(true);
		}
		if(st[m].equals("Account"))
		{
			mEmployeeModifyCheckBoxAccount.setSelected(true);
		}
		if(st[m].equals("Employee"))
		{
			mEmployeeModifyCheckBoxEmployee.setSelected(true);
		}
	}
                    
            mEmployeeModifyTextFieldName.setText(rs.getString(24));
                    mEmployeeModifyTextFieldContactNo1.setText(rs.getString(25));
                   mEmployeeModifyTextFieldEmail1.setText(rs.getString(26));
                  mEmployeeModifyTextFieldRelationship.setText(rs.getString(27));
                     String id = rs.getString(16);
	  String path = "photos/"+id+".jpg";    
	
	Image oimg = Toolkit.getDefaultToolkit().getImage(path);
	Image simg = oimg.getScaledInstance(100,100,Image.SCALE_DEFAULT);   
	mEmployelabelPhoto.setIcon(new ImageIcon(simg));
          
            }
}
                catch(Exception e)
                {
                    e.printStackTrace();
                }





        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void mEmployeeModifyTextFieldAddessLine1ActionPerformed(java.awt.event.ActionEvent evt) {                                                                    
        // TODO add your handling code here:
    }                                                                   

    private void mEmployeeModifyTextFieldAddessLine2ActionPerformed(java.awt.event.ActionEvent evt) {                                                                    
        // TODO add your handling code here:
    }                                                                   

    private void mEmployeeModifyTextFieldTownActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void mEmployeeModifyTextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mEmployeeModifyTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        // TODO add your handling code here:
    }                                                               

    private void mEmployeeModifyTextFieldZIPCodeActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        // TODO add your handling code here:
    }                                                               

    private void mEmployeeModifyTextFieldAlternateContactNoActionPerformed(java.awt.event.ActionEvent evt) {                                                                           
        // TODO add your handling code here:
    }                                                                          

    private void mEmployeeModifyTextFieldContactNoActionPerformed(java.awt.event.ActionEvent evt) {                                                                  
        // TODO add your handling code here:
    }                                                                 

    private void mEmployeeModifyTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    mEmployeModifyTextFieldAadharNumber.setText("");
    mEmployeeModifyTextFieldAddessLine1.setText("");
    mEmployeeModifyTextFieldAddessLine2.setText("");
    mEmployeeModifyTextFieldAlternateContactNo.setText("");
    mEmployeeModifyTextFieldContactNo.setText("");
    mEmployeeModifyTextFieldContactNo1.setText("");
    mEmployeeModifyTextFieldCountry.setText("");
    mEmployeeModifyTextFieldDesignation.setText("");
    mEmployeeModifyTextFieldEmail.setText("");
    mEmployeeModifyTextFieldEmail1.setText("");
    mEmployeeModifyTextFieldEmployeeID.setText("");
    mEmployeeModifyTextFieldFirstName.setText("");
    mEmployeeModifyTextFieldLastName.setText("");
    mEmployeeModifyTextFieldName.setText("");
    mEmployeeModifyTextFieldNationality.setText("");
    mEmployeeModifyTextFieldRelationship.setText("");
    mEmployeeModifyTextFieldSalary.setText("");
    mEmployeeModifyTextFieldState.setText("");
    mEmployeeModifyTextFieldTown.setText("");
    mEmployeeModifyTextFieldZIPCode.setText("");
      mEmployeeModifyCheckBoxInvoice.setSelected(false);
     mEmployeeModifyCheckBoxInventory.setSelected(false);
    mEmployeeModifyCheckBoxAccount.setSelected(false);
    mEmployeeModifyCheckBoxEmployee.setSelected(false);
  
    mEmployeeModifyComboBoxDate.setSelectedIndex(0);
    mModifyEmployeeComboBoxDate1.setSelectedIndex(0);
    mEmployeeModifyComboBoxMonth.setSelectedIndex(0);
    mModifyEmployeeComboBoxMonth1.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear1.setSelectedIndex(0);
    mEmployeeModifyComboBoxDepartment.setSelectedIndex(0);
    mEmployeeModifyComboBoxSalary.setSelectedIndex(0);
    mEmployeeModifyComboBoxSupervisor.setSelectedIndex(0);
    mEmployeeModifyComboBoxWorkLocation.setSelectedIndex(0);
    bg.clearSelection();
    mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));

// TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        

	              try
                                           {
  			String value = JOptionPane.showInputDialog(new JFrame(),"Enter Leaving Date (DD-MMM-YYYY)");
                                 		

			if(!(value.equals("")))
			{
			Connection con = dao.createconnection();
			PreparedStatement ps4 = con.prepareStatement("update employee1 set Status=?,Leave_Date=? where EmployeeId=?");
			ps4.setString(1,"Unavaliable");
			ps4.setString(2,value);
			ps4.setString(3,mEmployeeModifyTextFieldEmployeeID.getText());
			int z1=ps4.executeUpdate();	
			if(z1>0)
			{
				
    mEmployeModifyTextFieldAadharNumber.setText("");
    mEmployeeModifyTextFieldAddessLine1.setText("");
    mEmployeeModifyTextFieldAddessLine2.setText("");
    mEmployeeModifyTextFieldAlternateContactNo.setText("");
    mEmployeeModifyTextFieldContactNo.setText("");
    mEmployeeModifyTextFieldContactNo1.setText("");
    mEmployeeModifyTextFieldCountry.setText("");
    mEmployeeModifyTextFieldDesignation.setText("");
    mEmployeeModifyTextFieldEmail.setText("");
    mEmployeeModifyTextFieldEmail1.setText("");
    mEmployeeModifyTextFieldEmployeeID.setText("");
    mEmployeeModifyTextFieldFirstName.setText("");
    mEmployeeModifyTextFieldLastName.setText("");
    mEmployeeModifyTextFieldName.setText("");
    mEmployeeModifyTextFieldNationality.setText("");
    mEmployeeModifyTextFieldRelationship.setText("");
    mEmployeeModifyTextFieldSalary.setText("");
    mEmployeeModifyTextFieldState.setText("");
    mEmployeeModifyTextFieldTown.setText("");
    mEmployeeModifyTextFieldZIPCode.setText("");
      mEmployeeModifyCheckBoxInvoice.setSelected(false);
     mEmployeeModifyCheckBoxInventory.setSelected(false);
    mEmployeeModifyCheckBoxAccount.setSelected(false);
    mEmployeeModifyCheckBoxEmployee.setSelected(false);
  
    mEmployeeModifyComboBoxDate.setSelectedIndex(0);
    mModifyEmployeeComboBoxDate1.setSelectedIndex(0);
    mEmployeeModifyComboBoxMonth.setSelectedIndex(0);
    mModifyEmployeeComboBoxMonth1.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear1.setSelectedIndex(0);
    mEmployeeModifyComboBoxDepartment.setSelectedIndex(0);
    mEmployeeModifyComboBoxSalary.setSelectedIndex(0);
    mEmployeeModifyComboBoxSupervisor.setSelectedIndex(0);
    mEmployeeModifyComboBoxWorkLocation.setSelectedIndex(0);
    bg.clearSelection();
    mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));


				
				JOptionPane.showMessageDialog(new JFrame(),"Status changed successfully");
			}
			}
		       }
		catch(Exception e){}





// TODO add your handling code here:
    }                                        

    private void mEmployeeModifyTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mEmployeeModifyTextFieldEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {                                                                   
        // TODO add your handling code here:
    }                                                                  

    private void mEmployeeModifyTextFieldDesignationActionPerformed(java.awt.event.ActionEvent evt) {                                                                    
        // TODO add your handling code here:
    }                                                                   

    private void mEmployeeModifyTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void mEmployeeModifyTextFieldContactNo1ActionPerformed(java.awt.event.ActionEvent evt) {                                                                   
        // TODO add your handling code here:
    }                                                                  

    private void mEmployeeModifyTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mEmployeeModifyTextFieldRelationshipActionPerformed(java.awt.event.ActionEvent evt) {                                                                     
        // TODO add your handling code here:
    }                                                                    

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         

     if((mEmployeeModifyTextFieldAddessLine1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Address Line1 can't be empty");
        }
    else if((mEmployeeModifyTextFieldAddessLine2.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Address Line2 can't be empty");
        }
    else if((mEmployeeModifyTextFieldTown.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Town/city name can't be empty");
        }
    else if((mEmployeeModifyTextFieldState.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"State can't be empty");
        }
    else if((mEmployeeModifyTextFieldCountry.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Country can't be empty");
        }
    else if((mEmployeeModifyTextFieldZIPCode.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"ZIP code can't be empty");
        }
    else if((mEmployeeModifyTextFieldContactNo.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Contact number can't be empty");
        }
    else if((mEmployeeModifyTextFieldEmail.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Email can't be empty");
        }
    else if((mEmployeeModifyTextFieldDesignation.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Designation can't be empty");
        }
    else if((mEmployeeModifyTextFieldSalary.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Salary can't be empty");
        }
    else if((mEmployeeModifyTextFieldName.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Name can't be empty");
        }
    else if((mEmployeeModifyTextFieldContactNo1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Contact number can't be empty");
        }
    else if((mEmployeeModifyTextFieldEmail1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Email can't be empty");
        }
    else if((mEmployeeModifyTextFieldRelationship.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Relationship can't be empty");
        }
    else if((mEmployeeModifyComboBoxDepartment.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Department");
        }
    else if((mEmployeeModifyComboBoxWorkLocation.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Work Location");
        }
    else if((mEmployeeModifyComboBoxSalary.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Salary Unit");
        }
    else if((mEmployeeModifyComboBoxSupervisor.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Supervisor");
        }
    
    else if((mEmployeeModifyTextFieldContactNo1.getText().trim().length()<10))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid Contact number ");
        }
    else if((mEmployeeModifyTextFieldContactNo.getText().trim().length()<10))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid Contact number ");
        }
    else if((mEmployeeModifyTextFieldZIPCode.getText().trim().length()<6))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid Zip Code ");
        }
    
    else
    
    {
		try
                                           {
  			Connection con = dao.createconnection();
			PreparedStatement ps5 = con.prepareStatement("update employee1 set AddressLine1=?, AddressLine2=?,Town=?,State=?,Country=?,ZipCode=?,ContactNo=?,AltContact=?,Email=?,Designation=?,Department=?,Work_Location=?,Salary=?,Supervisor=?,Access_Rights=?,Emergency_Name=?,Emergency_Contact=?,Emergency_Email=?,Relationship=? where EmployeeId=?");
			ps5.setString(1,mEmployeeModifyTextFieldAddessLine1.getText());
			ps5.setString(2,mEmployeeModifyTextFieldAddessLine2.getText());
			ps5.setString(3,mEmployeeModifyTextFieldTown.getText());
			ps5.setString(4,mEmployeeModifyTextFieldState.getText());
			ps5.setString(5,mEmployeeModifyTextFieldCountry.getText());
			ps5.setString(6,mEmployeeModifyTextFieldZIPCode.getText());
			ps5.setString(7,mEmployeeModifyTextFieldContactNo.getText());
			ps5.setString(8,mEmployeeModifyTextFieldAlternateContactNo.getText());
			ps5.setString(9,mEmployeeModifyTextFieldEmail.getText());
			ps5.setString(10,mEmployeeModifyTextFieldDesignation.getText());
			ps5.setString(11, (String) mEmployeeModifyComboBoxDepartment.getSelectedItem());
			ps5.setString(12,(String) mEmployeeModifyComboBoxWorkLocation.getSelectedItem());
			ps5.setString(13,mEmployeeModifyTextFieldSalary.getText()+" "+(String)mEmployeeModifyComboBoxSalary.getSelectedItem());
			ps5.setString(14,(String)mEmployeeModifyComboBoxSupervisor.getSelectedItem());
			
			
	if(mEmployeeModifyCheckBoxInvoice.isSelected())
               {
	access=access+"Invoice ";
               }
               
	if(mEmployeeModifyCheckBoxInventory.isSelected())
               {
	access=access+"Inventory ";
               }
	if(mEmployeeModifyCheckBoxAccount.isSelected())
               {
	access=access+"Account ";
               }
	if(mEmployeeModifyCheckBoxEmployee.isSelected())
               {
	access=access+"Employee ";
               }

		


			ps5.setString(15,access);
			ps5.setString(16,mEmployeeModifyTextFieldName.getText());
			ps5.setString(17,mEmployeeModifyTextFieldContactNo1.getText());
			ps5.setString(18,mEmployeeModifyTextFieldEmail1.getText());
			ps5.setString(19,mEmployeeModifyTextFieldRelationship.getText());
			ps5.setString(20,mEmployeeModifyTextFieldEmployeeID.getText());
			int z=ps5.executeUpdate();
			String id=mEmployeeModifyTextFieldEmployeeID.getText();				
			if(m==1){
			File fe = new File("photos/"+id+".jpg");
			fe.delete();	
			
			File source = new File(path);
			File dest = new File("photos/"+mEmployeeModifyTextFieldEmployeeID.getText()+".jpg");      
			Files.copy(source.toPath(),dest.toPath());
			}

			if(z>0)
			{
	

    mEmployeModifyTextFieldAadharNumber.setText("");
    mEmployeeModifyTextFieldAddessLine1.setText("");
    mEmployeeModifyTextFieldAddessLine2.setText("");
    mEmployeeModifyTextFieldAlternateContactNo.setText("");
    mEmployeeModifyTextFieldContactNo.setText("");
    mEmployeeModifyTextFieldContactNo1.setText("");
    mEmployeeModifyTextFieldCountry.setText("");
    mEmployeeModifyTextFieldDesignation.setText("");
    mEmployeeModifyTextFieldEmail.setText("");
    mEmployeeModifyTextFieldEmail1.setText("");
    mEmployeeModifyTextFieldEmployeeID.setText("");
    mEmployeeModifyTextFieldFirstName.setText("");
    mEmployeeModifyTextFieldLastName.setText("");
    mEmployeeModifyTextFieldName.setText("");
    mEmployeeModifyTextFieldNationality.setText("");
    mEmployeeModifyTextFieldRelationship.setText("");
    mEmployeeModifyTextFieldSalary.setText("");
    mEmployeeModifyTextFieldState.setText("");
    mEmployeeModifyTextFieldTown.setText("");
    mEmployeeModifyTextFieldZIPCode.setText("");
    mEmployeeModifyCheckBoxInvoice.setSelected(false);
     mEmployeeModifyCheckBoxInventory.setSelected(false);
    mEmployeeModifyCheckBoxAccount.setSelected(false);
    mEmployeeModifyCheckBoxEmployee.setSelected(false);
   mEmployeeModifyComboBoxDate.setSelectedIndex(0);
    mModifyEmployeeComboBoxDate1.setSelectedIndex(0);
    mEmployeeModifyComboBoxMonth.setSelectedIndex(0);
    mModifyEmployeeComboBoxMonth1.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear.setSelectedIndex(0);
    mModifyEmployeeComboBoxYear1.setSelectedIndex(0);
    mEmployeeModifyComboBoxDepartment.setSelectedIndex(0);
    mEmployeeModifyComboBoxSalary.setSelectedIndex(0);
    mEmployeeModifyComboBoxSupervisor.setSelectedIndex(0);
    mEmployeeModifyComboBoxWorkLocation.setSelectedIndex(0);
    bg.clearSelection();
    mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));

				JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Record Updated Successfully");	
			}				



		      }		
			catch(Exception e)	
			{
				System.out.print(e);
			}
			

  
    }
    




        // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
if(p==1){
        dispose();
        fr.setEnabled(true);
       
}
else{
        dispose();
       new EmployeeDashboard(fr).setVisible(true);
}   
 }                                        

    private void mEmployeeModifyComboBoxWorkLocationActionPerformed(java.awt.event.ActionEvent evt) {                                                                    
        // TODO add your handling code here:
    }                                                                   

    private void mEmployeeModifyRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    private void mEmployeeModifyCheckBoxInvoiceActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mEmployeeModifyCheckBoxInventoryActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    private void mEmployeeModifyCheckBoxAccountActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mEmployeeModifyCheckBoxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        // TODO add your handling code here:
    }                                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeModify("lucky9898",0,new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
     private javax.swing.ButtonGroup bg;
     private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mAddVendorTextFieldFirstName1;
    private javax.swing.JTextField mEmployeModifyTextFieldAadharNumber;
    private javax.swing.JCheckBox mEmployeeModifyCheckBoxAccount;
    private javax.swing.JCheckBox mEmployeeModifyCheckBoxEmployee;
    private javax.swing.JCheckBox mEmployeeModifyCheckBoxInventory;
    private javax.swing.JCheckBox mEmployeeModifyCheckBoxInvoice;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxDate;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxDepartment;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxMonth;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxSalary;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxSupervisor;
    private javax.swing.JComboBox<String> mEmployeeModifyComboBoxWorkLocation;
    private javax.swing.JRadioButton mEmployeeModifyRadioButtonFemale;
    private javax.swing.JRadioButton mEmployeeModifyRadioButtonMale;
    private javax.swing.JTextField mEmployeeModifyTextFieldAddessLine1;
    private javax.swing.JTextField mEmployeeModifyTextFieldAddessLine2;
    private javax.swing.JTextField mEmployeeModifyTextFieldAlternateContactNo;
    private javax.swing.JTextField mEmployeeModifyTextFieldContactNo;
    private javax.swing.JTextField mEmployeeModifyTextFieldContactNo1;
    private javax.swing.JTextField mEmployeeModifyTextFieldCountry;
    private javax.swing.JTextField mEmployeeModifyTextFieldDesignation;
    private javax.swing.JTextField mEmployeeModifyTextFieldEmail;
    private javax.swing.JTextField mEmployeeModifyTextFieldEmail1;
    private javax.swing.JTextField mEmployeeModifyTextFieldEmployeeID;
    private javax.swing.JTextField mEmployeeModifyTextFieldFirstName;
    private javax.swing.JTextField mEmployeeModifyTextFieldLastName;
    private javax.swing.JTextField mEmployeeModifyTextFieldName;
    private javax.swing.JTextField mEmployeeModifyTextFieldNationality;
    private javax.swing.JTextField mEmployeeModifyTextFieldRelationship;
    private javax.swing.JTextField mEmployeeModifyTextFieldSalary;
    private javax.swing.JTextField mEmployeeModifyTextFieldState;
    private javax.swing.JTextField mEmployeeModifyTextFieldTown;
    private javax.swing.JTextField mEmployeeModifyTextFieldZIPCode;
    private javax.swing.JLabel mEmployelabelBrowse;
    private javax.swing.JLabel mEmployelabelPhoto;
    private javax.swing.JLabel mEmployelabelReset;
    private javax.swing.JComboBox<String> mModifyEmployeeComboBoxDate1;
    private javax.swing.JComboBox<String> mModifyEmployeeComboBoxMonth1;
    private javax.swing.JComboBox<String> mModifyEmployeeComboBoxYear;
    private javax.swing.JComboBox<String> mModifyEmployeeComboBoxYear1;
    // End of variables declaration                   
}

