/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.*;
import java.awt.FileDialog;
import java.awt.Image;
import java.awt.Toolkit;
import javax.*;
import javax.swing.ButtonGroup;
import java.io.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.sql.*;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import java.awt.Cursor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Employe extends javax.swing.JFrame {
int m=0;
String path;
String access="";
Image oimg,simg;
int p;
JFrame fr; 
    /**
     * Creates new form 
     */
    public Employe(int t,JFrame ft) {
p=t;
fr=ft;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(245,245,245));
  setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/add.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mEmployelabelPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mEmployeTextFieldFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mEmployeTextFieldLastName = new javax.swing.JTextField();
        mEmployelabelBrowse = new javax.swing.JLabel();
        mEmployeRadioButtonFemale = new javax.swing.JRadioButton();
        mEmployRadioButtonMale = new javax.swing.JRadioButton();
        mEmployeTextFieldNationality = new javax.swing.JTextField();
        mEmployeTextFieldAadharNumber = new javax.swing.JTextField();
        mEmployeComboBoxDate = new javax.swing.JComboBox<>();
        mEmployeComboBoxMonth = new javax.swing.JComboBox<>();
        mEmployeComboBoxYear = new javax.swing.JComboBox<>();
        mEmployelabelReset = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mEmployeTextFieldAddressLine1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mEmployeTextFieldAddressLine2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mEmployeTextFieldTown = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mEmployeTextFieldState1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mEmployeTextFieldCountry1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mEmployeTextFieldZIPCode = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        mEmployeTextFieldAlternateContactNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mEmployeTextFieldContactNo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        mEmployeTextFieldEmail = new javax.swing.JTextField();
        mEmployeButtonReset = new javax.swing.JButton();
        mEmployeButtonFinish = new javax.swing.JButton();
        mEmployeButtonCanel = new javax.swing.JButton();
        mAddVendorTextFieldFirstName1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        mEmployeTextFieldSalary = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mEmployeTextFieldEmployeeID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        mEmployeCombpBoxDepartment = new javax.swing.JComboBox<>();
        mEmployeCombpBoxWorkLocation = new javax.swing.JComboBox<>();
        mEmployeCombpBoxSalary = new javax.swing.JComboBox<>();
        mEmployeCombpBoxSupervisor = new javax.swing.JComboBox<>();
        mEmployeTextFieldDesignation = new javax.swing.JTextField();
        mEmployeComboBoxDate1 = new javax.swing.JComboBox<>();
        mEmployeComboBoxMonth1 = new javax.swing.JComboBox<>();
        mEmployeComboBoxYear1 = new javax.swing.JComboBox<>();
        mEmployeCheckBoxInvoice = new javax.swing.JCheckBox();
        mEmployeCheckBoxInventory = new javax.swing.JCheckBox();
        mEmployeCheckBoxIAccount = new javax.swing.JCheckBox();
        mEmployeCheckBoxEmployee = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        mEmployeTextFieldName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        mEmployeTextFieldContactNo1 = new javax.swing.JTextField();
        mEmployeTextFieldEmail1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        mEmployeTextFieldRelationship = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        jRadioButton1.setText("jRadioButton1");

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent){
                if(p==0)
                {
                    dispose();
                    new EmployeeDashboard(fr).setVisible(true);
                }
                else
                {
                    dispose();
                    fr.setEnabled(true);
                }
         }        
      });  
        setTitle("New Employee Registration");
        setBounds(new java.awt.Rectangle(307, 60, 762, 722));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(790, 730));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(760, 730));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        mEmployelabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/new user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        mEmployeTextFieldFirstName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });

mEmployeTextFieldFirstName.addFocusListener(new FocusAdapter()
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{

				if(!(mEmployeTextFieldAadharNumber.getText().trim().equals(""))){
				String s=mEmployeTextFieldAadharNumber.getText();
				String s1=s.substring(8,12);
				String s2=mEmployeTextFieldFirstName.getText();		
				mEmployeTextFieldEmployeeID.setText(s2+s1);
				}
			}	
		});
        mEmployeTextFieldLastName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });
        

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Nationality");
        mEmployeTextFieldNationality.addKeyListener(new KeyAdapter() 
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });
        

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Date of Birth");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Aadhar Number");
        mEmployeTextFieldAadharNumber.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldAadharNumber.getText().length()>11)
                {
                   e.consume();
                }
               
            }
        });
mEmployeTextFieldAadharNumber.addFocusListener(new FocusAdapter()
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{

				if(!(mEmployeTextFieldFirstName.getText().trim().equals(""))){
				String s=mEmployeTextFieldAadharNumber.getText();
				String s1=s.substring(8,12);
				String s2=mEmployeTextFieldFirstName.getText();		
				mEmployeTextFieldEmployeeID.setText(s2+s1);
				}
			}	
		});
mEmployelabelReset.setToolTipText("Reset Photo");
	mEmployelabelReset.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mEmployelabelBrowse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployelabelBrowse.setForeground(new java.awt.Color(0, 0, 255));
        mEmployelabelBrowse.setText("<html><u>Browse</u></html>");
         	mEmployelabelBrowse.setToolTipText("Browse Photo");
	mEmployelabelBrowse.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mEmployelabelBrowse.addMouseListener(new MouseAdapter()
	{   
	  
              
		public void mouseClicked(MouseEvent me)
		{
			FileDialog fd = new FileDialog(new javax.swing.JFrame (),"Choose Photo",FileDialog.LOAD);
			fd.setVisible(true);
			path = fd.getDirectory()+fd.getFile();
			if(!path.equals("nullnull"))
			{
				oimg = Toolkit.getDefaultToolkit().getImage(path);	
				simg = oimg.getScaledInstance(100,100,Image.SCALE_DEFAULT);   
				ImageIcon icon = new ImageIcon(simg);
				mEmployelabelPhoto.setIcon(icon); 
				m=1;
			}
		}
	});	


        mEmployelabelReset.addMouseListener(new MouseAdapter()
	{   
	  
              
		public void mouseClicked(MouseEvent me)
		{
      			mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));
		}
	});

        mEmployeRadioButtonFemale.setText("Female");
        mEmployeRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeRadioButtonFemaleActionPerformed(evt);
            }
        });
        bg=new ButtonGroup();
        bg.add(mEmployeRadioButtonFemale);
        bg.add(mEmployRadioButtonMale);

        mEmployRadioButtonMale.setText("Male");

        mEmployeComboBoxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mEmployeComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        mEmployeComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        mEmployelabelReset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployelabelReset.setForeground(new java.awt.Color(0, 0, 255));
        mEmployelabelReset.setText("<html><u>Reset</u></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployelabelPhoto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mEmployelabelBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(mEmployelabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(107, 107, 107))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(mEmployeTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mEmployeTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mEmployRadioButtonMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mEmployeRadioButtonFemale))
                            .addComponent(jLabel3)
                            .addComponent(mEmployeTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mEmployeComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mEmployeComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mEmployeComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mEmployeTextFieldAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mEmployeComboBoxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mEmployeComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mEmployeComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mEmployeTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mEmployeTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4))
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mEmployRadioButtonMale)
                            .addComponent(mEmployeTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mEmployeRadioButtonFemale)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mEmployeTextFieldAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mEmployelabelPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployelabelBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployelabelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel7.setText("Address Line 1");

        mEmployeTextFieldAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldAddressLine1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Address Line 2");

        mEmployeTextFieldAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldAddressLine2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Town/City");

        mEmployeTextFieldTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldTownActionPerformed(evt);
            }
        });
        mEmployeTextFieldTown.addKeyListener(new KeyAdapter()       // validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });

        jLabel12.setText("State");

        mEmployeTextFieldState1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldState1ActionPerformed(evt);
            }
        });
        mEmployeTextFieldState1.addKeyListener(new KeyAdapter()             //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });
        

        jLabel13.setText("Country");
        mEmployeTextFieldCountry1.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(!((c<'0') || (c>'9')))
                {
                    e.consume();//ignore event
                }
                
            }
        });

        mEmployeTextFieldCountry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldCountry1ActionPerformed(evt);
            }
        });

        jLabel14.setText("ZIP Code");

        mEmployeTextFieldZIPCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldZIPCodeActionPerformed(evt);
            }
        });
        mEmployeTextFieldZIPCode.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldZIPCode.getText().length()>5)
                {
                   e.consume();
                }
               
            }
        });

        jLabel25.setText("Email");

        mEmployeTextFieldAlternateContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldAlternateContactNoActionPerformed(evt);
            }
        });

        jLabel19.setText("Contact No");

        mEmployeTextFieldContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldContactNoActionPerformed(evt);
            }
        });
        mEmployeTextFieldContactNo.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldContactNo.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });

        jLabel35.setText("Alternate Contact No");

        mEmployeTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldEmailActionPerformed(evt);
            }
        });
  mEmployeTextFieldAlternateContactNo.addKeyListener(new KeyAdapter()       //validation
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldAlternateContactNo.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });


    mEmployeTextFieldEmail.addFocusListener(new FocusAdapter()      //validation
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{
				if(mEmployeTextFieldEmail.getText().trim().length()>0)
        				{
        			        Pattern pattern3 = Pattern.compile("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$", Pattern.CASE_INSENSITIVE);
           				Matcher m3=pattern3.matcher(mEmployeTextFieldEmail.getText());
           				Boolean b3=m3.matches();
           				if(b3!=true)
           				{
           				    JOptionPane.showMessageDialog(new JFrame(),"Invalid Email Address");
           				}
      			}
		}	
		});
        
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mEmployeTextFieldState1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(mEmployeTextFieldAddressLine1))
                            .addComponent(mEmployeTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(mEmployeTextFieldAlternateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mEmployeTextFieldCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(mEmployeTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addComponent(jLabel25)
                                .addComponent(mEmployeTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(mEmployeTextFieldZIPCode)
                                .addComponent(mEmployeTextFieldTown)))
                        .addGap(20, 20, 20))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeTextFieldAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeTextFieldState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldZIPCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel35)
                    .addComponent(jLabel25))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldAlternateContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mEmployeButtonReset.setBackground(new java.awt.Color(245, 245, 245));
        mEmployeButtonReset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployeButtonReset.setText("Reset");
      mEmployeButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeButtonResetActionPerformed(evt);
            }
        });


	mEmployeButtonReset.setToolTipText("Reset");
	mEmployeButtonReset.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        mEmployeButtonFinish.setBackground(new java.awt.Color(245, 245, 245));
        mEmployeButtonFinish.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployeButtonFinish.setText("Finish");
        mEmployeButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeButtonFinishActionPerformed(evt);
            }
        });
mEmployeButtonFinish.setToolTipText("Finish");
	mEmployeButtonFinish.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        mEmployeButtonCanel.setBackground(new java.awt.Color(245, 245, 245));
        mEmployeButtonCanel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mEmployeButtonCanel.setText("Cancel");
        mEmployeButtonCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeButtonCanelActionPerformed(evt);
            }
        });
mEmployeButtonCanel.setToolTipText("Cancel");
	mEmployeButtonCanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        mAddVendorTextFieldFirstName1.setBackground(new java.awt.Color(245, 245, 245));
        mAddVendorTextFieldFirstName1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Job Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel15.setText("Designation");

        mEmployeTextFieldSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldSalaryActionPerformed(evt);
            }
        });

        jLabel16.setText("Work Location");

        jLabel20.setText("Supervisor");

        jLabel22.setText("Salary");
        mEmployeTextFieldSalary.addKeyListener(new KeyAdapter()            //pincode validaion
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldSalary.getText().length()>7)
                {
                   e.consume();
                }
               
            }
        });
        

        jLabel23.setText("Employee ID");

        mEmployeTextFieldEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldEmployeeIDActionPerformed(evt);
            }
        });

mEmployeTextFieldEmployeeID.setEditable(false);

        jLabel24.setText("Department");

        jLabel29.setText("Date of Joining");

        jLabel31.setText("Acess Rights");

        mEmployeCombpBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Production", "Quality", "Sales and Purchasing","IT","Health and Safety","Technical Planning","Corporate Support","Accounting" }));

        mEmployeCombpBoxWorkLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Godown", "House", "Factory" }));

        mEmployeCombpBoxSalary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "per day", "per month" }));

     //   mEmployeCombpBoxSupervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05", "06", "07", "08", "09", "100" }));

        mEmployeTextFieldDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldDesignationActionPerformed(evt);
            }
        });
     		mEmployeCombpBoxSupervisor.addItem("Select");
		  try
				{
					Connection con = dao.createconnection();
					PreparedStatement ps0 = con.prepareStatement("select * from employee1");
					ResultSet rs0 = ps0.executeQuery();
					while(rs0.next())
					{
					String id=rs0.getString(16);
					mEmployeCombpBoxSupervisor.addItem(""+id);
					}
				
					
				}
				catch(Exception ee)
				{
				}


        mEmployeTextFieldDesignation.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)))
               {
                    e.consume();//ignore event
                }
                
            }
        });



        mEmployeComboBoxDate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mEmployeComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        mEmployeComboBoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        mEmployeCheckBoxInvoice.setText("Invoicing");
        mEmployeCheckBoxInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeCheckBoxInvoiceActionPerformed(evt);
            }
        });

        mEmployeCheckBoxInventory.setText("Inventory");
        mEmployeCheckBoxInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeCheckBoxInventoryActionPerformed(evt);
            }
        });

        mEmployeCheckBoxIAccount.setText("Accounts");
        mEmployeCheckBoxIAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeCheckBoxIAccountActionPerformed(evt);
            }
        });

        mEmployeCheckBoxEmployee.setText("Employee");
        mEmployeCheckBoxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeCheckBoxEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mAddVendorTextFieldFirstName1Layout = new javax.swing.GroupLayout(mAddVendorTextFieldFirstName1);
        mAddVendorTextFieldFirstName1.setLayout(mAddVendorTextFieldFirstName1Layout);
        mAddVendorTextFieldFirstName1Layout.setHorizontalGroup(
            mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mEmployeCombpBoxWorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mEmployeComboBoxDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mEmployeComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mEmployeComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel31)
                                        .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                            .addComponent(mEmployeTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(mEmployeCombpBoxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(20, 20, 20))
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                    .addComponent(mEmployeCheckBoxInvoice)
                                    .addGap(10, 10, 10))))
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mEmployeCheckBoxInventory)
                            .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel16)
                                    .addComponent(mEmployeTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel15)
                                    .addComponent(mEmployeTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mEmployeCombpBoxSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mEmployeCombpBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                            .addComponent(mEmployeCheckBoxIAccount)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mEmployeCheckBoxEmployee)))
                    .addComponent(jLabel24))
                .addGap(26, 26, 26))
        );
        mAddVendorTextFieldFirstName1Layout.setVerticalGroup(
            mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mAddVendorTextFieldFirstName1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeCombpBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeCombpBoxWorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeCombpBoxSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeCombpBoxSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(mAddVendorTextFieldFirstName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeComboBoxDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeCheckBoxInvoice)
                    .addComponent(mEmployeCheckBoxInventory)
                    .addComponent(mEmployeCheckBoxIAccount)
                    .addComponent(mEmployeCheckBoxEmployee))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Emergency Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel30.setText("Name");

        mEmployeTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldNameActionPerformed(evt);
            }
        });
        mEmployeTextFieldName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)) && (c!=KeyEvent.VK_BACK_SPACE))
               {
                    e.consume();//ignore event
                }
                
            }
        });
        


        mEmployeTextFieldContactNo1.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
                char c=e.getKeyChar();
                if(((c<'0') || (c>'9')) && (c!=KeyEvent.VK_BACK_SPACE))
                {
                    e.consume();//ignore event
                }
                else if(mEmployeTextFieldContactNo1.getText().length()>9)
                {
                   e.consume();
                }
               
            }
        });

        jLabel32.setText("Contact No");

        jLabel33.setText("Email");

        mEmployeTextFieldContactNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldContactNo1ActionPerformed(evt);
            }
        });
        mEmployeTextFieldEmail1.addFocusListener(new FocusAdapter()
		{
			public void focusGained(FocusEvent fe)
			{
			}
			public void focusLost(FocusEvent fe)
			{
				if(mEmployeTextFieldEmail1.getText().trim().length()>0)
        				{
        			                   Pattern pattern3 = Pattern.compile("^[\\w-\\+]+(\\.[\\w]+)*@[\\w-]+(\\.[\\w]+)*(\\.[a-z]{2,})$", Pattern.CASE_INSENSITIVE);
           				Matcher m3=pattern3.matcher(mEmployeTextFieldEmail1.getText());
           				Boolean b3=m3.matches();
           				if(b3!=true)
           				{
           				    JOptionPane.showMessageDialog(new JFrame(),"Invalid Email Address");
           				}
      			}
		}	
		});

        mEmployeTextFieldRelationship.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
               char c=e.getKeyChar();
         
                if((!Character.isLetter(c)))
               {
                    e.consume();//ignore event
                }
                
            }
        });


        mEmployeTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldEmail1ActionPerformed(evt);
            }
        });

        jLabel34.setText("Relationship");

        mEmployeTextFieldRelationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeTextFieldRelationshipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployeTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployeTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mEmployeTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(mEmployeTextFieldRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEmployeTextFieldRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mEmployeButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mEmployeButtonCanel)
                        .addGap(18, 18, 18)
                        .addComponent(mEmployeButtonFinish))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mAddVendorTextFieldFirstName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mAddVendorTextFieldFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mEmployeButtonReset)
                    .addComponent(mEmployeButtonCanel)
                    .addComponent(mEmployeButtonFinish))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void mEmployeTextFieldAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mEmployeTextFieldAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mEmployeTextFieldTownActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void mEmployeTextFieldState1ActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void mEmployeTextFieldCountry1ActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void mEmployeTextFieldZIPCodeActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void mEmployeTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void mEmployeTextFieldEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

    private void mEmployeTextFieldAlternateContactNoActionPerformed(java.awt.event.ActionEvent evt) {                                                                    
        // TODO add your handling code here:
    }                                                                   

    private void mEmployeTextFieldContactNoActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void mEmployeTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void mEmployeTextFieldContactNo1ActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

    private void mEmployeTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void mEmployeTextFieldRelationshipActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mEmployeButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {                                                     
    
   if(m==0)
		{
		JOptionPane.showMessageDialog(new JFrame(),"Photo must be selected");
		}
   else if((mEmployeTextFieldFirstName.getText().trim().equals(""))) 
        {
            JOptionPane.showMessageDialog(new JFrame(),"First name can't be empty");
        }
    else if((mEmployeTextFieldLastName.getText().trim().equals(""))) 
        {
            JOptionPane.showMessageDialog(new JFrame(),"Last Name can't be empty");
        }
    else if((mEmployeTextFieldNationality.getText().trim().equals(""))) 
        {
            JOptionPane.showMessageDialog(new JFrame(),"Nationality can't be empty");
        }
    else if(!(mEmployRadioButtonMale.isSelected() || mEmployeRadioButtonFemale.isSelected()))
    {
    JOptionPane.showMessageDialog(new JFrame(),"Gender can't leave blank");
    }
   else if((mEmployeTextFieldAadharNumber.getText().trim().equals(""))) 
        {
            JOptionPane.showMessageDialog(new JFrame(),"Aadhar Number can't be empty");
        }
    else if((mEmployeTextFieldAddressLine1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Address Line1 can't be empty");
        }
    else if((mEmployeTextFieldAddressLine2.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Address Line2 can't be empty");
        }
    else if((mEmployeTextFieldTown.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Town/city name can't be empty");
        }
    else if((mEmployeTextFieldState1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"State can't be empty");
        }
    else if((mEmployeTextFieldCountry1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Country can't be empty");
        }
    else if((mEmployeTextFieldZIPCode.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"ZIP code can't be empty");
        }
    else if((mEmployeTextFieldContactNo.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Contact number can't be empty");
        }
    else if((mEmployeTextFieldEmail.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Email can't be empty");
        }
    else if((mEmployeTextFieldDesignation.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Designation can't be empty");
        }
    else if((mEmployeTextFieldSalary.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Salary can't be empty");
        }
    else if((mEmployeTextFieldName.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Name can't be empty");
        }
    else if((mEmployeTextFieldContactNo1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Contact number can't be empty");
        }
 else if((!(mEmployeTextFieldAlternateContactNo.getText().equals(""))) && mEmployeTextFieldAlternateContactNo.getText().length()<10)
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid Alternate Contact No");
        }
    else if((mEmployeTextFieldEmail1.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Email can't be empty");
        }
    else if((mEmployeTextFieldRelationship.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Relationship can't be empty");
        }
    else if((mEmployeCombpBoxDepartment.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Department");
        }
    else if((mEmployeCombpBoxWorkLocation.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Work Location");
        }
    else if((mEmployeCombpBoxSalary.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Salary Unit");
        }
    else if((mEmployeCombpBoxSupervisor.getSelectedItem().toString().equals("Select")))
        {
            JOptionPane.showMessageDialog(new JFrame(),"Select Supervisor");
        }
    else if(mEmployeTextFieldContactNo.getText().trim().length()<10)
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid  Contact Number");
        }
    else if(mEmployeTextFieldAadharNumber.getText().trim().length()<12)
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid  Aadhar No");
        }
      else if(mEmployeTextFieldZIPCode.getText().trim().length()<6)
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid  Zip Code");
        }
else if(mEmployeTextFieldContactNo1.getText().trim().length()<10)
        {
            JOptionPane.showMessageDialog(new JFrame(),"Invalid  Contact Number");
        }
    else
    
    {
        // MY DATABASE WORK
        		
		try
			{
			Connection con = dao.createconnection();
			PreparedStatement ps = con.prepareStatement("insert into employee1 values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
					
		ps.setString(1,mEmployeTextFieldFirstName.getText() );
		ps.setString(2,mEmployeTextFieldLastName.getText() );
		ps.setString(3,(String)mEmployeComboBoxDate.getSelectedItem()+"-"+(String)mEmployeComboBoxMonth.getSelectedItem()+"-"+(String)mEmployeComboBoxYear.getSelectedItem());
		ps.setString(4,mEmployeTextFieldNationality.getText() );
                		
		String gen;
		if(mEmployeRadioButtonFemale.isSelected())
		{
			gen = "Female";
		}
		else
		{
			gen = "Male";
		}

		ps.setString(5,gen);
                		ps.setString(6,mEmployeTextFieldAadharNumber.getText() );
                ps.setString(7,mEmployeTextFieldAddressLine1.getText() );
                ps.setString(8,mEmployeTextFieldAddressLine2.getText() );
                ps.setString(9,mEmployeTextFieldTown.getText() );
                ps.setString(10,mEmployeTextFieldState1.getText());
                ps.setString(11, mEmployeTextFieldCountry1.getText());
                ps.setString(12, mEmployeTextFieldZIPCode.getText() );
                 ps.setString(13,mEmployeTextFieldContactNo.getText());
                ps.setString(14, mEmployeTextFieldAlternateContactNo.getText() );
                ps.setString(15,mEmployeTextFieldEmail.getText() );
                String s=mEmployeTextFieldAadharNumber.getText();
                ps.setString(16,mEmployeTextFieldFirstName.getText()+s.substring(8,12) );
                ps.setString(17,mEmployeTextFieldDesignation.getText() );
                ps.setString(18, (String) mEmployeCombpBoxDepartment.getSelectedItem());
                ps.setString(19, (String) mEmployeCombpBoxWorkLocation.getSelectedItem());
                ps.setString(20,mEmployeTextFieldSalary.getText()+" "+(String)mEmployeCombpBoxSalary.getSelectedItem() );
                ps.setString(21, (String) mEmployeCombpBoxSupervisor.getSelectedItem());
               ps.setString(22,(String)mEmployeComboBoxDate1.getSelectedItem()+"-"+ (String)mEmployeComboBoxMonth1.getSelectedItem()+"-"+(String)mEmployeComboBoxYear1.getSelectedItem());
                

	if(mEmployeCheckBoxInvoice.isSelected())
               {
	access=access+"Invoice ";
               }
               
	if(mEmployeCheckBoxInventory.isSelected())
               {
	access=access+"Inventory ";
               }
	if(mEmployeCheckBoxIAccount.isSelected())
               {
	access=access+"Account ";
               }
	if(mEmployeCheckBoxEmployee.isSelected())
               {
	access=access+"Employee ";
               }
                 
                 ps.setString(23,access);
                 ps.setString(24,mEmployeTextFieldName.getText());
                  ps.setString(25,mEmployeTextFieldContactNo1.getText() );
                   ps.setString(26,mEmployeTextFieldEmail1.getText() );
                    ps.setString(27,mEmployeTextFieldRelationship.getText() );
                     ps.setString(28,"");
                      ps.setString(29, "AVAILABLE");
                       ps.setString(30,"xyz@123" );
	int flag=ps.executeUpdate();
		
		if(flag==1)
		{
                                                        JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Record Inserted Successfully");			
                                                        File source = new File(path);
							File dest = new File("photos/"+mEmployeTextFieldEmployeeID.getText()+".jpg");      
							Files.copy(source.toPath(),dest.toPath());

		mEmployeTextFieldAadharNumber.setText("");
    mEmployeTextFieldAddressLine1.setText("");
    mEmployeTextFieldAddressLine2.setText("");
    mEmployeTextFieldAlternateContactNo.setText("");
    mEmployeTextFieldContactNo.setText("");
    mEmployeTextFieldContactNo1.setText("");
    mEmployeTextFieldCountry1.setText("");
    mEmployeTextFieldDesignation.setText("");
    mEmployeTextFieldEmail.setText("");
    mEmployeTextFieldEmail1.setText("");
    mEmployeTextFieldEmployeeID.setText("");
    mEmployeTextFieldFirstName.setText("");
    mEmployeTextFieldLastName.setText("");
    mEmployeTextFieldName.setText("");
    mEmployeTextFieldNationality.setText("");
    mEmployeTextFieldRelationship.setText("");
    mEmployeTextFieldSalary.setText("");
    mEmployeTextFieldState1.setText("");
    mEmployeTextFieldTown.setText("");
    mEmployeTextFieldZIPCode.setText("");
    mEmployeCheckBoxInventory.setSelected(false);
    mEmployeCheckBoxInvoice.setSelected(false);
    mEmployeCheckBoxIAccount.setSelected(false);
    mEmployeCheckBoxEmployee.setSelected(false);
    mEmployeComboBoxDate.setSelectedIndex(0);
    mEmployeComboBoxDate1.setSelectedIndex(0);
    mEmployeComboBoxMonth.setSelectedIndex(0);
    mEmployeComboBoxMonth1.setSelectedIndex(0);
    mEmployeComboBoxYear.setSelectedIndex(0);
    mEmployeComboBoxYear1.setSelectedIndex(0);
    mEmployeCombpBoxDepartment.setSelectedIndex(0);
    mEmployeCombpBoxSalary.setSelectedIndex(0);
    mEmployeCombpBoxSupervisor.setSelectedIndex(0);
    mEmployeCombpBoxWorkLocation.setSelectedIndex(0);
    bg.clearSelection();
    mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));
                                			
		}
		else
		{
			System.out.println("record not inserted.....");
		}
	   }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(new JFrame(),"please install mycorru in any drive except c ");
	        }
    
    }
    
   

   // TODO add your handling code here:
    }                                                    

    private void mEmployeTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void mEmployeTextFieldDesignationActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            
    private void mEmployeButtonResetActionPerformed(java.awt.event.ActionEvent evt) {                                                    
   mEmployeTextFieldAadharNumber.setText("");
    mEmployeTextFieldAddressLine1.setText("");
    mEmployeTextFieldAddressLine2.setText("");
    mEmployeTextFieldAlternateContactNo.setText("");
    mEmployeTextFieldContactNo.setText("");
    mEmployeTextFieldContactNo1.setText("");
    mEmployeTextFieldCountry1.setText("");
    mEmployeTextFieldDesignation.setText("");
    mEmployeTextFieldEmail.setText("");
    mEmployeTextFieldEmail1.setText("");
    mEmployeTextFieldEmployeeID.setText("");
    mEmployeTextFieldFirstName.setText("");
    mEmployeTextFieldLastName.setText("");
    mEmployeTextFieldName.setText("");
    mEmployeTextFieldNationality.setText("");
    mEmployeTextFieldRelationship.setText("");
    mEmployeTextFieldSalary.setText("");
    mEmployeTextFieldState1.setText("");
    mEmployeTextFieldTown.setText("");
    mEmployeTextFieldZIPCode.setText("");
    
    mEmployeCheckBoxInventory.setSelected(false);
    mEmployeCheckBoxInvoice.setSelected(false);
    mEmployeCheckBoxIAccount.setSelected(false);
    mEmployeCheckBoxEmployee.setSelected(false);

    mEmployeComboBoxDate.setSelectedIndex(0);
    mEmployeComboBoxDate1.setSelectedIndex(0);
    mEmployeComboBoxMonth.setSelectedIndex(0);
    mEmployeComboBoxMonth1.setSelectedIndex(0);
    mEmployeComboBoxYear.setSelectedIndex(0);
    mEmployeComboBoxYear1.setSelectedIndex(0);
    mEmployeCombpBoxDepartment.setSelectedIndex(0);
    mEmployeCombpBoxSalary.setSelectedIndex(0);
    mEmployeCombpBoxSupervisor.setSelectedIndex(0);
    mEmployeCombpBoxWorkLocation.setSelectedIndex(0);
    bg.clearSelection(); 
    mEmployelabelPhoto.setIcon(new ImageIcon(getClass().getResource("images/new user.png")));
    

    }                                                   

    private void mEmployeButtonCanelActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        if(p==1){
dispose();
fr.setEnabled(true);

}
else{
dispose();
new EmployeeDashboard(fr).setVisible(true);
}
    }                                                   

    private void mEmployeRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void mEmployeCheckBoxInvoiceActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void mEmployeCheckBoxInventoryActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void mEmployeCheckBoxIAccountActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void mEmployeCheckBoxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employe(0,new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify    
    private javax.swing.ButtonGroup bg;                 
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mAddVendorTextFieldFirstName1;
    private javax.swing.JRadioButton mEmployRadioButtonMale;
    private javax.swing.JButton mEmployeButtonCanel;
    private javax.swing.JButton mEmployeButtonFinish;
    private javax.swing.JButton mEmployeButtonReset;
    private javax.swing.JCheckBox mEmployeCheckBoxEmployee;
    private javax.swing.JCheckBox mEmployeCheckBoxIAccount;
    private javax.swing.JCheckBox mEmployeCheckBoxInventory;
    private javax.swing.JCheckBox mEmployeCheckBoxInvoice;
    private javax.swing.JComboBox<String> mEmployeComboBoxDate;
    private javax.swing.JComboBox<String> mEmployeComboBoxDate1;
    private javax.swing.JComboBox<String> mEmployeComboBoxMonth;
    private javax.swing.JComboBox<String> mEmployeComboBoxMonth1;
    private javax.swing.JComboBox<String> mEmployeComboBoxYear;
    private javax.swing.JComboBox<String> mEmployeComboBoxYear1;
    private javax.swing.JComboBox<String> mEmployeCombpBoxDepartment;
    private javax.swing.JComboBox<String> mEmployeCombpBoxSalary;
    private javax.swing.JComboBox<String> mEmployeCombpBoxSupervisor;
    private javax.swing.JComboBox<String> mEmployeCombpBoxWorkLocation;
    private javax.swing.JRadioButton mEmployeRadioButtonFemale;
    private javax.swing.JTextField mEmployeTextFieldAadharNumber;
    private javax.swing.JTextField mEmployeTextFieldAddressLine1;
    private javax.swing.JTextField mEmployeTextFieldAddressLine2;
    private javax.swing.JTextField mEmployeTextFieldAlternateContactNo;
    private javax.swing.JTextField mEmployeTextFieldContactNo;
    private javax.swing.JTextField mEmployeTextFieldContactNo1;
    private javax.swing.JTextField mEmployeTextFieldCountry1;
    private javax.swing.JTextField mEmployeTextFieldDesignation;
    private javax.swing.JTextField mEmployeTextFieldEmail;
    private javax.swing.JTextField mEmployeTextFieldEmail1;
    private javax.swing.JTextField mEmployeTextFieldEmployeeID;
    private javax.swing.JTextField mEmployeTextFieldFirstName;
    private javax.swing.JTextField mEmployeTextFieldLastName;
    private javax.swing.JTextField mEmployeTextFieldName;
    private javax.swing.JTextField mEmployeTextFieldNationality;
    private javax.swing.JTextField mEmployeTextFieldRelationship;
    private javax.swing.JTextField mEmployeTextFieldSalary;
    private javax.swing.JTextField mEmployeTextFieldState1;
    private javax.swing.JTextField mEmployeTextFieldTown;
    private javax.swing.JTextField mEmployeTextFieldZIPCode;
    private javax.swing.JLabel mEmployelabelBrowse;
    private javax.swing.JLabel mEmployelabelPhoto;
    private javax.swing.JLabel mEmployelabelReset;
    // End of variables declaration                   
}
