/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

import javax.swing.table.AbstractTableModel;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ashok
 */
public class PINumber1 extends javax.swing.JFrame {
Connection con;
String aa="";
JFrame fr;
    /**
     * Creates new form PINumber
     */
    public PINumber1(JFrame ft) {
        fr=ft;
        setTitle("Purchase Order And Invoice Numbers");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent){
               dispose();
               fr.setEnabled(true);
         }        
      });  
        setBackground(new java.awt.Color(245, 245, 245));

        jTabbedPane1.setBackground(new java.awt.Color(245, 245, 245));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PO No.", "PO Date", "Vendor Name", "Vendor Id", "Contact No."
            }
        ));
        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Purchase Order Numbers", jPanel1);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No.", "Invoice Date", "Client Name", "Contact No.", "Aadhar No."
            }
        ));
        jTable2.setEnabled(false);
        jTable1.setEnabled(false);
        jTable3.setEnabled(false);
        TableCellRenderer rendererFromHeader2 = jTable2.getTableHeader().getDefaultRenderer();
        JLabel headerLabel2 = (JLabel) rendererFromHeader2;
        headerLabel2.setHorizontalAlignment(JLabel.CENTER);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Client Invoice Numbers", jPanel2);

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No.", "Delivery Date", "Vendor Name", "Vendor Id", "Contact No."
            }
        ));
        TableCellRenderer rendererFromHeader3 = jTable3.getTableHeader().getDefaultRenderer();
        JLabel headerLabel3 = (JLabel) rendererFromHeader3;
        headerLabel3.setHorizontalAlignment(JLabel.CENTER);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

try{
    con = dao.createconnection();
}   
catch(Exception e){}

try{
 PreparedStatement ps1 = con.prepareStatement("select * from extra1 ");
ResultSet rs=ps1.executeQuery();					
while(rs.next())
{
 PreparedStatement ps2 = con.prepareStatement("select * from Req where Invoice_No=?");
    ps2.setString(1,rs.getString(1));
ResultSet rs2=ps2.executeQuery();
if(rs2.next())
{
aa=rs2.getString(2);
}
PreparedStatement ps3 = con.prepareStatement("select * from NewClient where AadharNo=?");
    ps3.setString(1,aa);
ResultSet rs3=ps3.executeQuery();
if(rs3.next())
{
   String name=rs3.getString(1)+" "+rs3.getString(2);
   String cont=rs3.getString(13);
 
   DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
   model.addRow(new Object[]{rs.getString(1),rs.getString(2),name,cont,aa});
      
}


}
}   
catch(Exception e){System.out.println(e);}

try{
PreparedStatement ps1 = con.prepareStatement("select * from PurchaseOrder2 where PO_NO!=?");
ps1.setString(1,"");
ResultSet rs=ps1.executeQuery();					
while(rs.next())
{
PreparedStatement ps2 = con.prepareStatement("select * from details where Vendor_id=?");
ps2.setString(1,rs.getString(2));
ResultSet rs2=ps2.executeQuery();
if(rs2.next())
{
DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
   model.addRow(new Object[]{rs.getString(1),rs.getString(3),rs2.getString(10)+" "+rs2.getString(11),rs.getString(2),rs2.getString(12)});
}
    
}
}
 catch(Exception e1)
 {
     System.out.print(e1);
 }       


try{
PreparedStatement ps1 = con.prepareStatement("select * from PurchaseOrder2 where Invoice_No!=?");
ps1.setString(1,"");
ResultSet rs=ps1.executeQuery();					
while(rs.next())
{
PreparedStatement ps2 = con.prepareStatement("select * from details where Vendor_id=?");
ps2.setString(1,rs.getString(2));
ResultSet rs2=ps2.executeQuery();
if(rs2.next())
{
DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
   model.addRow(new Object[]{rs.getString(7),rs.getString(4),rs2.getString(10)+" "+rs2.getString(11),rs.getString(2),rs2.getString(12)});
}
    
}
}
 catch(Exception e2)
 {
     System.out.print(e2);
 }       
 
jTabbedPane1.addTab("Vendor Invoice Number", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PINumber1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PINumber1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PINumber1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PINumber1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PINumber1(new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration                   
}
