/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package micpro;

import java.lang.Object;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.table.*;
import javax.swing.border.TitledBorder;
import javax.swing.BorderFactory;
import javax.swing.border.Border; 
import java.sql.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.TableCellRenderer;

/* 
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class PurchaseOrder extends javax.swing.JFrame  {
String PODate;
JFrame ff;
JFrame fr;
static int i=1;
int a=0;
String vid;
String id;
  Connection con1;
  /**
     * Creates new form PurchaseOrder
     */
    public PurchaseOrder(JFrame ft) {
      fr=ft;
      mno(this);
      initComponents();
        setTitle("Purchase Order");
        getContentPane().setBackground(new java.awt.Color(245,245,245) );
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/po.png")));
       setLocation(306,75);
    }
public void mno(JFrame fm)
{
    ff=fm;
}
public static void def(String u,String v,String w,String x)
{
 mAddVendorTextFieldCompanyName.setText(u);
mAddVendorTextFieldContactNo1.setText(v);
mAddVendorTextFieldEmail1.setText(w);
mPurchaseOrderComboBoxSelect.addItem(x);
mPurchaseOrderComboBoxSelect.setSelectedItem(x);
JOptionPane.showMessageDialog(new JFrame(),"Vendor details added successfully ");						
						
}
public static void abc(String x,String y,String z)
{
  DefaultTableModel model=(DefaultTableModel)mAddVendorTable.getModel();
   model.addRow(new Object[]{i,x,y,z});
      i++;
 
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mAddVendorTextFieldCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mAddVendorTextFieldContactNo1 = new javax.swing.JTextField();
        mAddVendorTextFieldEmail1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mAddVendorButtonCreateOrder1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mPurchaseOrderComboBoxSelect = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        mAddVendorButtonSheets = new javax.swing.JButton();
        mAddVendorButtonColor = new javax.swing.JButton();
        mAddVendorButtonTapes = new javax.swing.JButton();
        mAddVendorButtonGlue = new javax.swing.JButton();
        mAddVendorButtonPins = new javax.swing.JButton();
        mAddVendorButtonCreateOrder = new javax.swing.JButton();
        mAddVendorButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mAddVendorTable = new javax.swing.JTable();
        mAddVendorButtonDelete = new javax.swing.JButton();
        mAddVendorButtonReset = new javax.swing.JButton();

        checkbox1.setLabel("checkbox1");
try{
     con1 = dao.createconnection();
}
catch(Exception e)
{
    
}    
mPurchaseOrderComboBoxSelect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
               
                 mPurchaseOrderComboBoxSelect = (JComboBox) event.getSource();

                String selected = (String)mPurchaseOrderComboBoxSelect.getSelectedItem();
try
				{
					
					PreparedStatement ps = con1.prepareStatement("select * from details where Vendor_id=?");
					ps.setString(1,selected);
					ResultSet rs = ps.executeQuery();
					if(rs.next())
					{
						mAddVendorTextFieldCompanyName.setText(rs.getString(1));
						mAddVendorTextFieldContactNo1.setText(rs.getString(2));
						mAddVendorTextFieldEmail1.setText(rs.getString(3));
						
					}
					else
					{
					//System.out.print("error");
					}
					//con1.close();				
				}
				catch(Exception ee)
				{
					System.out.println(ee);
				}				
             


/*   if(selected.toString().equals("item1"))
                field.setText("30");
                else if(selected.toString().equals("item2"))
                    field.setText("40");
*/
            }
        });



       addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent){
               dispose(); 
                new InventoryDashboard(fr).setVisible((true));
         }        
      });     


//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Order");
        setBackground(new java.awt.Color(245, 245, 245));
        setBounds(new java.awt.Rectangle(306, 40, 753, 469));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vendor Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Select Vendor Using Vendor Id");

        mAddVendorTextFieldCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorTextFieldCompanyNameActionPerformed(evt);
            }
        });
       mAddVendorTextFieldCompanyName.setEditable(false);

        jLabel2.setText("Contact No");

        jLabel5.setText("Email");

        mAddVendorTextFieldContactNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorTextFieldContactNo1ActionPerformed(evt);
            }
        });
       mAddVendorTextFieldContactNo1.setEditable(false);

        mAddVendorTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorTextFieldEmail1ActionPerformed(evt);
            }
        });
       mAddVendorTextFieldEmail1.setEditable(false);

        jLabel7.setText("Company Name");

        mAddVendorButtonCreateOrder1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonCreateOrder1.setText("New Vendor Registration");
        mAddVendorButtonCreateOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonCreateOrder1ActionPerformed(evt);
            }
        });

        jLabel4.setText("OR");

//        mPurchaseOrderComboBoxSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c", "d", " " }));

mPurchaseOrderComboBoxSelect.addItem("Select")	;			
			try
				{
					//Connection con = dao.createconnection();
					PreparedStatement ps1 = con1.prepareStatement("select * from details ");
					ResultSet rs = ps1.executeQuery();
					while(rs.next())
					{
					String id=rs.getString(25);
					mPurchaseOrderComboBoxSelect.addItem(""+id);
					}
				
					
				}
				catch(Exception ee)
				{
				}







        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(mAddVendorTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mPurchaseOrderComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mAddVendorTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(mAddVendorTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mAddVendorButtonCreateOrder1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAddVendorButtonCreateOrder1)
                    .addComponent(jLabel4)
                    .addComponent(mPurchaseOrderComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAddVendorTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorTextFieldContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Add Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 255))); // NOI18N

               mAddVendorButtonSheets.setBackground(new java.awt.Color(241, 239, 241));
        mAddVendorButtonSheets.setFont(new java.awt.Font("Segoe UI", 0, 12));
        mAddVendorButtonSheets.setBorderPainted(false);
        mAddVendorButtonSheets.setToolTipText("sheets");
        mAddVendorButtonSheets.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mAddVendorButtonSheets.addMouseListener(new MouseAdapter()
		{
			public void mouseEntered(MouseEvent me)
			{
			mAddVendorButtonSheets.setBackground(new Color(160,160,160)); 
			}
			public void mouseExited(MouseEvent me)
			{
				mAddVendorButtonSheets.setBackground(new Color(241,239,241));
			}
			public void mouseClicked(MouseEvent me)
			{
				
			}
		});           



      mAddVendorButtonSheets.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/f.png"))); // NOI18N
        mAddVendorButtonSheets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonSheetsActionPerformed(evt);
            }
        });



        mAddVendorButtonColor.setBackground(new java.awt.Color(241, 239, 241));
        mAddVendorButtonColor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonColor.setBorderPainted(false);
       mAddVendorButtonColor.setToolTipText("Dye");
	mAddVendorButtonColor.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mAddVendorButtonColor.addMouseListener(new MouseAdapter()
		{
			public void mouseEntered(MouseEvent me)
			{
			mAddVendorButtonColor.setBackground(new Color(160,160,160)); 
			}
			public void mouseExited(MouseEvent me)
			{
				mAddVendorButtonColor.setBackground(new Color(241,239,241));
			}
			public void mouseClicked(MouseEvent me)
			{
				
			}
		});           

        
mAddVendorButtonColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/e.png"))); // NOI18N
        mAddVendorButtonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonColorActionPerformed(evt);
            }
        });

        mAddVendorButtonTapes.setBackground(new java.awt.Color(241, 239, 241));
        mAddVendorButtonTapes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonTapes.setBorderPainted(false);
        mAddVendorButtonTapes.setToolTipText("Tapes");
	mAddVendorButtonTapes.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mAddVendorButtonTapes.addMouseListener(new MouseAdapter()
		{
			public void mouseEntered(MouseEvent me)
			{
			mAddVendorButtonTapes.setBackground(new Color(160,160,160)); 
			}
			public void mouseExited(MouseEvent me)
			{
				mAddVendorButtonTapes.setBackground(new Color(241,239,241));
			}
			public void mouseClicked(MouseEvent me)
			{
				
			}
		});     
        mAddVendorButtonTapes.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/c.png"))); // NOI18N
        mAddVendorButtonTapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonTapesActionPerformed(evt);
            }
        });

        mAddVendorButtonGlue.setBackground(new java.awt.Color(241, 239, 241));
        mAddVendorButtonGlue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonGlue.setBorderPainted(false);
        mAddVendorButtonGlue.setToolTipText("Glue");
	mAddVendorButtonGlue.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mAddVendorButtonGlue.addMouseListener(new MouseAdapter()
		{
			public void mouseEntered(MouseEvent me)
			{
			mAddVendorButtonGlue.setBackground(new Color(160,160,160)); 
			}
			public void mouseExited(MouseEvent me)
			{
				mAddVendorButtonGlue.setBackground(new Color(241,239,241));
			}
			public void mouseClicked(MouseEvent me)
			{
				
			}
		});     

        mAddVendorButtonGlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/d.png"))); // NOI18N
        mAddVendorButtonGlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonGlueActionPerformed(evt);
            }
        });

        mAddVendorButtonPins.setBackground(new java.awt.Color(241, 239, 241));
        mAddVendorButtonPins.setFont(new java.awt.Font("Segoe UI", 0, 12));
        mAddVendorButtonPins.setBorderPainted(false);
        mAddVendorButtonPins.setToolTipText("Pins");
	mAddVendorButtonPins.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        mAddVendorButtonPins.addMouseListener(new MouseAdapter()
		{
			public void mouseEntered(MouseEvent me)
			{
			mAddVendorButtonPins.setBackground(new Color(160,160,160)); 
			}
			public void mouseExited(MouseEvent me)
			{
				mAddVendorButtonPins.setBackground(new Color(241,239,241));
			}
			public void mouseClicked(MouseEvent me)
			{
				
			}
		});     

        mAddVendorButtonPins.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/b.png"))); // NOI18N
        mAddVendorButtonPins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonPinsActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mAddVendorButtonSheets, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(mAddVendorButtonPins, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(mAddVendorButtonGlue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(mAddVendorButtonTapes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mAddVendorButtonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mAddVendorButtonSheets, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorButtonPins, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorButtonGlue, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorButtonColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAddVendorButtonTapes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mAddVendorButtonCreateOrder.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonCreateOrder.setText("Create Order");
        mAddVendorButtonCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonCreateOrderActionPerformed(evt);
            }
        });

        mAddVendorButtonCancel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonCancel.setText("Cancel");
        mAddVendorButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonCancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selected Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        mAddVendorTable.setAutoCreateRowSorter(true);
        mAddVendorTable.setBackground(new java.awt.Color(245, 245, 245));
        mAddVendorTable.setRowHeight(25);
        mAddVendorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {"Sr.No","Item","Description","Quantity"

            }
        ));

TableCellRenderer rendererFromHeader = mAddVendorTable.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);

mAddVendorTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
mAddVendorTable.getColumnModel().getColumn(0).setPreferredWidth(50);
mAddVendorTable.getColumnModel().getColumn(1).setPreferredWidth(80);
mAddVendorTable.getColumnModel().getColumn(2).setPreferredWidth(443);
mAddVendorTable.getColumnModel().getColumn(3).setPreferredWidth(100);


        jScrollPane1.setViewportView(mAddVendorTable);

        mAddVendorButtonDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonDelete.setText("Delete Selected Item");
        mAddVendorButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mAddVendorButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mAddVendorButtonDelete)
                .addGap(14, 14, 14))
        );

        mAddVendorButtonReset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mAddVendorButtonReset.setText("Reset");
        mAddVendorButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddVendorButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mAddVendorButtonCreateOrder)
                        .addGap(10, 10, 10)
                        .addComponent(mAddVendorButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(mAddVendorButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAddVendorButtonCancel)
                    .addComponent(mAddVendorButtonCreateOrder)
                    .addComponent(mAddVendorButtonReset))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>                        

    private void mAddVendorTextFieldCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void mAddVendorTextFieldContactNo1ActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void mAddVendorTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void mAddVendorButtonSheetsActionPerformed(java.awt.event.ActionEvent evt) {                                                       
ff.setEnabled(false);
     new Sheets(1,ff).setVisible(true); // TODO add your handling code here:
    }                                                      

    private void mAddVendorButtonColorActionPerformed(java.awt.event.ActionEvent evt) {                                                      
ff.setEnabled(false);// setEnabled(false);
     new Dye(1,ff).setVisible(true);        // TODO add your handling code here:
    }                                                     

    private void mAddVendorButtonTapesActionPerformed(java.awt.event.ActionEvent evt) {                                                      
ff.setEnabled(false);
     new Tapes(1,ff).setVisible(true);
  // TODO add your handling code here:
    }                                                     

    private void mAddVendorButtonGlueActionPerformed(java.awt.event.ActionEvent evt) {                                                     
//        setEnabled(false);
     new Glue(1,ff).setVisible(true);
     ff.setEnabled(false);
// TODO add your handling code here:
    }                                                    

    private void mAddVendorButtonPinsActionPerformed(java.awt.event.ActionEvent evt) {                                                     
     ff.setEnabled(false); // setEnabled(false);
     new StaplePins(1,ff).setVisible(true); // TODO add your handling code here:
    }                                                    

    private void mAddVendorButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       new InventoryDashboard(fr).setVisible(true);
 // TODO add your handling code here:
        dispose();
    }                                                      

    private void mAddVendorButtonCreateOrder1ActionPerformed(java.awt.event.ActionEvent evt) {                                                             
       int p=1;
    // setEnabled(false);
     new AddVendor(p,fr).setVisible(true);// TODO add your handling code here:
    }                                                            
    private void mAddVendorButtonCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {                                                            
DefaultTableModel model9=(DefaultTableModel)mAddVendorTable.getModel();
int xx=model9.getRowCount();       
String item6 =(String)mPurchaseOrderComboBoxSelect.getSelectedItem();

if(mAddVendorTextFieldCompanyName.getText().trim().equals(""))
{
JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please add vendor");
}
else if(xx==0)
{
JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please add some item");
}
else
{
// TODO add your handling code here:
   				try
				{
					
					//Connection con3 = dao.createconnection();
					PreparedStatement ps3 = con1.prepareStatement("select * from PurchaseOrder where PO_NO!=? ");
					ps3.setString(1," ");
					ResultSet rs3 = ps3.executeQuery();
					if(rs3.last())
					{
					id=rs3.getString(6);
					int vi=Integer.parseInt(id);
					vi=vi+1;
					vid=Integer.toString(vi);
					}
					else
					{
					vid="1" ; 
					}
					

				}
				catch(Exception e)	
				{
				
				}
				
				try
				{
					
					//Connection con1 = dao.createconnection();
					PreparedStatement ps1 = con1.prepareStatement("insert into PurchaseOrder values(?,?,?,?,?,?,?,?)");
					int j;
					DefaultTableModel model4=(DefaultTableModel)mAddVendorTable.getModel();
					int x=model4.getRowCount();
					for(j=0;j<x;j++)
					{
						String item =model4.getValueAt(j, 1).toString();
    					           	String desc=model4.getValueAt(j, 2).toString();
    					            	String quant=model4.getValueAt(j,3 ).toString();
    					            	ps1.setString(1,item);
    						ps1.setString(2,desc);
						ps1.setString(3,quant);
						ps1.setString(4,"");
    						ps1.setString(5,"");
						ps1.setString(7,"");
    						ps1.setString(8,"");
    						 						

						if(!(vid.equals("1")))
						{
						ps1.setString(6,vid);
    						}
						else{
						ps1.setString(6,"1");
						}
	
						int z1 =ps1.executeUpdate();
						if(z1>0)
						{
						//  JOptionPane.showMessageDialog(new JFrame(),"Order created successfully");
						}	
					}
					
			
				}
				catch(Exception e)
				{
					System.out.print(e);
				}
			

				try
				{
					
						String DATE_FORMAT = "dd-MMM-yyyy";
						SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
    						Calendar c1 = Calendar.getInstance();
       					                   PODate=sdf.format(c1.getTime());
						
						//Connection con2 = dao.createconnection();
						PreparedStatement ps2= con1.prepareStatement("insert into PurchaseOrder2 values(?,?,?,?,?,?,?,?,?)");
					           	

						if(!(vid.equals("1")))
						{
						ps2.setString(1,vid);
    						}
						else{
						ps2.setString(1,"1");
    						}
						ps2.setString(2,(String)mPurchaseOrderComboBoxSelect.getSelectedItem());
						ps2.setString(3,PODate);
						ps2.setString(4,"");
    						ps2.setString(5,"");
    						ps2.setString(6,"");
    						ps2.setString(7,"");
    						ps2.setString(8,"");
    						ps2.setString(9,"");
    						int z2 =ps2.executeUpdate();
						if(z2>0){
						 
						Object[] options = {"YES","NO"};
					int n = JOptionPane.showOptionDialog(null,
				            "Order Created Successfully\n Want To Print ?",
				            "Message",
				            JOptionPane.YES_NO_CANCEL_OPTION,
				            JOptionPane.DEFAULT_OPTION,
				            null,
				            options,
				            options[1]); 

					if(n==0){  
					String vendor=mAddVendorTextFieldEmail1.getText();
					

						if(!(vid.equals("1")))
						{
						dispose();
						new Print1(vendor,vid,PODate,fr).setVisible(true);					
						}
						else{
						dispose();
						new Print1(vendor,"1",PODate,fr).setVisible(true);					
						}

					
					}
					else if(n==1)
					{	 
					}
					else
					{
					} 
	
						 i=1;
    						mAddVendorTextFieldCompanyName.setText("");        
    						mAddVendorTextFieldContactNo1.setText("");        
    						mAddVendorTextFieldEmail1.setText("");        
    						 mPurchaseOrderComboBoxSelect.setSelectedIndex(0);
    						  DefaultTableModel model22=(DefaultTableModel)mAddVendorTable.getModel();
   						while(model22.getRowCount() > 0)
  						 {
  						       int i;
 						        for(i=0;i<model22.getRowCount();i++)
 						       { 
 						         model22.removeRow(i);
 						       }
 						    }

						//JOptionPane.showMessageDialog(new JFrame(),"Order created successfully");
						}
			
				}
				catch(Exception e)
				{
					System.out.print(e);
				
				}


		}


    }                                                           

    private void mAddVendorButtonResetActionPerformed(java.awt.event.ActionEvent evt) {                                                      

   i=1;
    mAddVendorTextFieldCompanyName.setText("");        
    mAddVendorTextFieldContactNo1.setText("");        
    mAddVendorTextFieldEmail1.setText("");        
     mPurchaseOrderComboBoxSelect.setSelectedIndex(0);
      DefaultTableModel model2=(DefaultTableModel)mAddVendorTable.getModel();
   while(model2.getRowCount() > 0)
   {
         int i;
         for(i=0;i<model2.getRowCount();i++)
        { 
          model2.removeRow(i);
        }
     }

// TODO add your handling code here:
    }
                                                     
    private void mAddVendorButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                                       
    
int a=JOptionPane.showConfirmDialog(new JFrame(),"Are you sure?");  
if(a==JOptionPane.YES_OPTION){  
try{
     DefaultTableModel model1=(DefaultTableModel)mAddVendorTable.getModel(); 
     int SelectedRowIndex=mAddVendorTable.getSelectedRow();
     
//i=1;
//DefaultTableModel model = (DefaultTableModel) this.mAddVendorTable.getModel();
  // int[] rows = mAddVendorTable.getSelectedRows();



int t;
int ss=SelectedRowIndex;
int rows1 = mAddVendorTable.getRowCount();
int sr=(int)mAddVendorTable.getModel().getValueAt(ss,0);
int m=rows1-sr;

model1.removeRow(SelectedRowIndex);


//   for(int i=0;i<rows.length;i++){
  // model.removeRow(rows[i]-i);
   //}


for(t=0;t<m;t++){
mAddVendorTable.setValueAt((Object)sr,ss,0);
sr++;
ss++;
}
}
catch(Exception e1){   JOptionPane.showMessageDialog(new JFrame(),"Plz select item first");}

} 

// TODO add your handling code here:
    }                                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseOrder(new JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mAddVendorButtonCancel;
    private javax.swing.JButton mAddVendorButtonColor;
    private javax.swing.JButton mAddVendorButtonCreateOrder;
    private javax.swing.JButton mAddVendorButtonCreateOrder1;
    private javax.swing.JButton mAddVendorButtonDelete;
    private javax.swing.JButton mAddVendorButtonGlue;
    private javax.swing.JButton mAddVendorButtonPins;
    private javax.swing.JButton mAddVendorButtonReset;
    private javax.swing.JButton mAddVendorButtonSheets;
    private javax.swing.JButton mAddVendorButtonTapes;
   public static javax.swing.JTable mAddVendorTable;
    public static javax.swing.JTextField mAddVendorTextFieldCompanyName;
    public static javax.swing.JTextField mAddVendorTextFieldContactNo1;
    public static javax.swing.JTextField mAddVendorTextFieldEmail1;
   public static javax.swing.JComboBox<String> mPurchaseOrderComboBoxSelect;
    // End of variables declaration                   
}

