package micpro;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.print.*;
 import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.sql.*;
        
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class TaxInvoice1 extends javax.swing.JFrame  implements Printable {
 JFrame frameToPrint;
  String id1;
 String ppu="";
 String amount="";
String gst="";
 JFrame fr;
      static JFrame SP = new TaxInvoice1("0015",new JFrame());

    /**
     * Creates new form NewJFrame
     */
    public TaxInvoice1(String id,JFrame ft) {
fr=ft;
      id1=id;
setLocation(350,25);
setTitle("Invoice");
setResizable(false);
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        
    }
 public TaxInvoice1(JFrame f){
        frameToPrint = f;
 
    }

 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mTaxInvoicelabelCompanyName = new javax.swing.JLabel();
        mTaxInvoicelabelAddressLine1 = new javax.swing.JLabel();
        mTaxInvoicelabelAddressLine2 = new javax.swing.JLabel();
        mTaxInvoicelabelPhoneNo = new javax.swing.JLabel();
        mTaxInvoicelabelEmail = new javax.swing.JLabel();
        mTaxInvoicelabelCompanyName12 = new javax.swing.JLabel();
        mTaxInvoicelabelAddressLine12 = new javax.swing.JLabel();
        mTaxInvoicelabelAddressLine22 = new javax.swing.JLabel();
        mTaxInvoicelabelPhoneNo2 = new javax.swing.JLabel();
        mTaxInvoicelabelEmail2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mTaxInvoicelabelCompanyName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mTaxInvoicelabelInvoiceNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mTaxInvoicelabelDate = new javax.swing.JLabel();
        mTaxInvoicelabelSubTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mTaxInvoicelabelTax = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mTaxInvoicelabelPayableAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

      //  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent windowEvent){
               dispose();
             new InvoiceDashboard(fr).setVisible(true);

         }        
      });    
        mTaxInvoicelabelCompanyName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mTaxInvoicelabelCompanyName.setText("Company Name");

        mTaxInvoicelabelAddressLine1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelAddressLine1.setText("Address Line 1");

        mTaxInvoicelabelAddressLine2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelAddressLine2.setText("Address Line 2");

        mTaxInvoicelabelPhoneNo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelPhoneNo.setText("Phone No");

        mTaxInvoicelabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelEmail.setText("Email");

        mTaxInvoicelabelCompanyName12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelCompanyName12.setText("Client Name");

        mTaxInvoicelabelAddressLine12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelAddressLine12.setText("Address Line 1");

        mTaxInvoicelabelAddressLine22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelAddressLine22.setText("Address Line 2");

        mTaxInvoicelabelPhoneNo2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelPhoneNo2.setText("Phone No");

        mTaxInvoicelabelEmail2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelEmail2.setText("Email");

        jPanel1.setBackground(new java.awt.Color(59, 71, 136));
        jPanel2.setBackground(new java.awt.Color(255,255,255));

        mTaxInvoicelabelCompanyName1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mTaxInvoicelabelCompanyName1.setForeground(new java.awt.Color(255, 255, 255));
        mTaxInvoicelabelCompanyName1.setText("Billing Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mTaxInvoicelabelCompanyName1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mTaxInvoicelabelCompanyName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setText("Invoice No");

        mTaxInvoicelabelInvoiceNo.setText("");

        jLabel4.setText("Date");

        mTaxInvoicelabelDate.setText("");

        mTaxInvoicelabelSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelSubTotal.setText("");

        jLabel7.setText("Tax (%)");

        mTaxInvoicelabelTax.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelTax.setText("");

        jLabel5.setText("Net Amount");

        mTaxInvoicelabelPayableAmount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mTaxInvoicelabelPayableAmount.setText("");

        jLabel3.setText("Sub Total");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Box Description", "Qty", "Unit Price", "GST (%)", "Total Amount"
            }
        ));
        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(138);
        jScrollPane2.setViewportView(jTable1);
        jTable1.setEnabled(false);
        
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/ggg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
jButton1.setToolTipText("Print");
	jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
jButton1.setFocusable(false);        
String aadhar="";
					
					try
					{
					Connection con = dao.createconnection();
					PreparedStatement ps = con.prepareStatement("select * from extra1 where InvoiceNo=?");
					ps.setString(1,id1);
					ResultSet rs = ps.executeQuery();
					if(rs.next())
					{
					mTaxInvoicelabelDate.setText(rs.getString(2));
					mTaxInvoicelabelInvoiceNo.setText(id1);
					mTaxInvoicelabelSubTotal.setText(rs.getString(5));
					mTaxInvoicelabelTax.setText(rs.getString(3));
					mTaxInvoicelabelPayableAmount.setText(rs.getString(4));
					
					PreparedStatement ps1 = con.prepareStatement("select * from Req where Invoice_No=?");
				   	ps1.setString(1,id1);
					ResultSet rs5 = ps1.executeQuery();
					while(rs5.next())
					{
					aadhar=rs5.getString(2);
					ppu=rs5.getString(11);
					amount=rs5.getString(12);
					gst=rs5.getString(13);
					 String proid=rs5.getString(1);
					 String type=rs5.getString(4);
					 String qty	=rs5.getString(6);				
					 DefaultTableModel model = (DefaultTableModel)jTable1.getModel();					
					 model.addRow(new Object[]{proid,type,qty,ppu,gst,amount});	
					 }
					PreparedStatement ps3 = con.prepareStatement("select * from NewClient where AadharNo=?");
				   	ps3.setString(1,aadhar);
					ResultSet rs3= ps3.executeQuery();
					if(rs3.next())
					{
					mTaxInvoicelabelAddressLine12.setText(rs3.getString(7)+" "+rs3.getString(8));
   					mTaxInvoicelabelAddressLine22.setText(rs3.getString(9)+", "+rs3.getString(10)+", "+rs3.getString(12));
    					mTaxInvoicelabelCompanyName12.setText(rs3.getString(1)+" "+rs3.getString(2));
    					mTaxInvoicelabelEmail2.setText(rs3.getString(15));
 					mTaxInvoicelabelPhoneNo2.setText(rs3.getString(13));
					}
					
					}


				      }
				catch(Exception e)
				{
					System.out.print(e);
				}

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mTaxInvoicelabelPhoneNo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelAddressLine22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelAddressLine12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelCompanyName12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelAddressLine2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelAddressLine1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelPhoneNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mTaxInvoicelabelCompanyName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mTaxInvoicelabelEmail2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mTaxInvoicelabelInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mTaxInvoicelabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mTaxInvoicelabelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTaxInvoicelabelSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mTaxInvoicelabelPayableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTaxInvoicelabelCompanyName)
                    .addComponent(jLabel2)
                    .addComponent(mTaxInvoicelabelInvoiceNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTaxInvoicelabelAddressLine1)
                    .addComponent(jLabel4)
                    .addComponent(mTaxInvoicelabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelAddressLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelPhoneNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelEmail)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mTaxInvoicelabelCompanyName12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelAddressLine12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelAddressLine22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelPhoneNo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mTaxInvoicelabelEmail2)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mTaxInvoicelabelSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(mTaxInvoicelabelTax))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mTaxInvoicelabelPayableAmount)
                    .addComponent(jButton1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         // TODO add your handling code here:
         
//        JOptionPane.showMessageDialog(null, "hello");
        PrinterJob PJ   =   PrinterJob.getPrinterJob();
        //PageFormat PF   =   PJ.pageDialog(PJ.defaultPage());
        PJ.setPrintable((Printable) this);
        boolean doPrint = PJ.printDialog();
 
        //JOptionPane.showMessageDialog(null, doPrint);
        if(doPrint){
            try {
                PJ.print();
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
           }
        } // TODO add your handling code here:
    }                                        
 public int print(Graphics g, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
          return(NO_SUCH_PAGE);
        } else {
          Graphics2D g2d = (Graphics2D)g;
          g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
          // Turn off double buffering
          //componentToBePrinted.paint(g2d);
          //frameToPrint.print(g);
          SP.print(g);
          // Turn double buffering back on
          return(PAGE_EXISTS);
        }
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              SP.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mTaxInvoicelabelAddressLine1;
    private javax.swing.JLabel mTaxInvoicelabelAddressLine12;
    private javax.swing.JLabel mTaxInvoicelabelAddressLine2;
    private javax.swing.JLabel mTaxInvoicelabelAddressLine22;
    private javax.swing.JLabel mTaxInvoicelabelCompanyName;
    private javax.swing.JLabel mTaxInvoicelabelCompanyName1;
    private javax.swing.JLabel mTaxInvoicelabelCompanyName12;
    private javax.swing.JLabel mTaxInvoicelabelDate;
    private javax.swing.JLabel mTaxInvoicelabelEmail;
    private javax.swing.JLabel mTaxInvoicelabelEmail2;
    private javax.swing.JLabel mTaxInvoicelabelInvoiceNo;
    private javax.swing.JLabel mTaxInvoicelabelPayableAmount;
    private javax.swing.JLabel mTaxInvoicelabelPhoneNo;
    private javax.swing.JLabel mTaxInvoicelabelPhoneNo2;
    private javax.swing.JLabel mTaxInvoicelabelSubTotal;
    private javax.swing.JLabel mTaxInvoicelabelTax;
    // End of variables declaration                   
}
